["0.0-1.2.2"]
julia = "0.3-0.6"

["0.0-1.3.2"]
TikzPictures = "0.0-1.2"

["0.0-1.3.5"]
Contour = "0.0-0.1"

["0.0.2-1.3"]
Images = "0.2-0.11"

["1.2.2-1.3"]
Colors = "0.4-0.8"

["1.2.2-1.3.5"]
Compat = "0.0-0.31"

["1.2.3-1.4"]
julia = "0.4-0.6"

["1.3.1-1.3.7"]
ColorBrewer = "0.1-0.3"

["1.3.3-1.3.5"]
TikzPictures = "0.3.2-1.2"

["1.3.3-1.4"]
ImageMagick = "0.0-0.5"

["1.3.6-1.5.0"]
Compat = "0.8-0.31"

["1.3.6-1.7"]
Contour = "0.2-0.4"
Discretizers = "0.0-2.1"
TikzPictures = "0.3.4-1.2"

["1.4"]
Images = "0.5.2-0.11"

["1.4-1.7"]
Colors = "0.6.7-0.8"

["1.4-2.0"]
ColorBrewer = "0.3"
StatsBase = "0.9-0.18"

["1.4.3-1.7"]
DataFrames = "0.8-0.10"
Reel = "0.1-1.0"

["1.5-1.7"]
julia = "0.5-0.6"
Images = "0.6-0.11"

["1.5-2.0"]
ImageMagick = "0.2.3-0.5"
IndirectArrays = "0.1.1"

["1.5.1-1.7"]
Compat = "0.17-0.31"

["2.0"]
julia = "0.6"
Colors = "0.8"
Contour = "0.4"
DataFrames = "0.9-0.10"
Discretizers = "2.0-2.1"
Images = "0.11"
Reel = "1.0.1"
TikzPictures = "1.1-1.2"
