["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.1"]
StochasticDiffEq = "0.0-2.11"

["0.0-0.2"]
julia = "0.5-0.6"

["0.1"]
DiffEqBase = "0.15-1.23"

["0.2"]
DiffEqBase = "1.0-1.23"
DiffEqNoiseProcess = "0.0-0.5"

["0.3"]
julia = "0.6"
DiffEqBase = "1.14-1.23"
DiffEqNoiseProcess = "0.3.1-0.5"
RandomNumbers = "0.0-0.1"
