["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.1"]
StochasticDiffEq = "0.0-2.20"

["0.0-0.2"]
julia = "0.5-0.6"

["0.1"]
DiffEqBase = "0.15-2.6"

["0.2"]
DiffEqBase = "1.0-2.6"
DiffEqNoiseProcess = "0.0-0.7"

["0.3"]
julia = "0.6"
DiffEqBase = "1.14-2.6"
DiffEqNoiseProcess = "0.3.1-0.7"
RandomNumbers = "0.0-0.1"
