["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.1"]
StochasticDiffEq = "0.0-2.23"

["0.0-0.2"]
julia = "0.5-0.6"

["0.1"]
DiffEqBase = "0.15-2.10"

["0.2"]
DiffEqBase = "1.0-2.10"
DiffEqNoiseProcess = "0.0-0.8"

["0.3"]
julia = "0.6"
DiffEqBase = "1.14-2.10"
DiffEqNoiseProcess = "0.3.1-0.8"
RandomNumbers = "0.0-0.1"
