["0.0"]
julia = "0.4-0.6"
GeometryTypes = "0.0-0.4"

["0.0-0.1"]
ColorTypes = "0.0-0.6"
FileIO = "0.0-0.6"

["0.0.1-0.0.4"]
Compat = "0.0-0.39"

["0.0.5"]
Compat = "0.7.15-0.39"

["0.0.6"]
Compat = "0.8.7-0.39"

["0.1"]
julia = "0.6"
GeometryTypes = "0.4"
