["0.0"]
julia = "0.4-0.6"
Compat = "0.9.1-0.33"

["0.0-0.1.1"]
FactCheck = "0.4.2-0.4.3"

["0.0.1"]
TaylorSeries = "0.2-0.6"

["0.0.2"]
TaylorSeries = "0.3-0.6"

["0.1"]
julia = "0.5-0.6"

["0.1.0-0.1.1"]
TaylorSeries = "0.5-0.6"

["0.1.2"]
TaylorSeries = "0.5.1-0.6"
