["0.1"]
julia = "0.4-0.6"

["0.1-0.2"]
ODE = "0.1-0.7"

["0.1-0.3"]
Distributions = "0.1-0.14"
JLD = "0.5-0.8"
JSON = "0.1-0.15"

["0.2-0.3"]
julia = "0.5-0.6"

["0.3"]
DifferentialEquations = "1.5-2.3"
