["0.0"]
julia = "0.4-0.7"

["0.0-0.1"]
DataStructures = "0.2-0.7"

["0.0.4-0.1"]
RecipesBase = "0.0-0.3"

["0.1-0.2"]
julia = "0.5-0.7"

["0.2-0.3.0"]
RecipesBase = "0.1-0.3"

["0.2-0.4"]
Compat = "0.17-0.52"
DataStructures = "0.5-0.7"

["0.3-0.4"]
julia = "0.6-0.7"

["0.3.1-0.4"]
RecipesBase = "0.2.3-0.3"
