["0.0"]
julia = "0.4-0.6"

["0.0-0.1"]
DataStructures = "0.2-0.6"

["0.0.4-0.1"]
RecipesBase = "0.0-0.2"

["0.1-0.2"]
julia = "0.5-0.6"

["0.2"]
Compat = "0.17-0.31"
DataStructures = "0.5-0.6"
RecipesBase = "0.1-0.2"
