["0.0"]
julia = "0.5-0.7"
MappedArrays = "0.0"
StatsBase = "0.1-0.19"

["0.0.1"]
LearnBase = "0.1.1-0.1.6"

["0.0.2-0.0.5"]
LearnBase = "0.1.5-0.1.6"

["0.1-0.2"]
julia = "0.6-0.7"
MappedArrays = "0.0.6-0.0.7"
StatsBase = "0.13-0.19"

["0.1.0"]
LearnBase = "0.1.3-0.1.6"

["0.1.1-0.2"]
LearnBase = "0.1.5-0.1.6"
