["0.0"]
julia = "0.3-0.5"
DualNumbers = "0.0-0.3"

["0.1-0.2"]
Calculus = "0.1-0.2"
NaNMath = "0.0-0.2"

["0.1.0-0.1.2"]
julia = "0.4-0.5"

["0.1.3-0.3.3"]
DiffBase = "0.0-0.2"

["0.1.3-0.3.4"]
julia = "0.4-0.6"

["0.2.0-0.2.1"]
Compat = "0.0-0.31"

["0.2.2-0.3"]
Compat = "0.8.6-0.31"

["0.3.0-0.3.3"]
Calculus = "0.1.15-0.2"
NaNMath = "0.2.1-0.2.6"

["0.3.4"]
Calculus = "0.2"
DiffBase = "0.0.3-0.2"
NaNMath = "0.2.2-0.2.6"

["0.3.5"]
julia = "0.4-0.5"
Calculus = "0.1.15-0.2"
DiffBase = "0.0-0.2"
NaNMath = "0.2.1-0.2.6"

["0.4"]
julia = "0.5-0.6"
Calculus = "0.2"
Compat = "0.19-0.31"
DiffBase = "0.0.3-0.2"

["0.4-0.5"]
NaNMath = "0.2.2-0.2.6"
SpecialFunctions = "0.1-0.3"

["0.5"]
julia = "0.6"
CommonSubexpressions = "0.0"
DiffBase = "0.2"
RealInterface = "0.0.2-0.0.3"
StaticArrays = "0.5-0.6"
