["0.1"]
julia = "0.6"
DiffEqBase = "0.0-1.23"
Interpolations = "0.0-0.7"
JuMP = "0.1-0.18"
OrdinaryDiffEq = "0.0-2.19"
Parameters = "0.0-0.8"
Ranges = "0.0"

["0.1.2"]
NLOptControl = "0.1"

["0.1.3"]
NLOptControl = "0.1.3"
