["0.0-0.2"]
DataFrames = "0.1-0.10"

["0.0.1"]
julia = "0.1-0.6"

["0.0.2-0.0.3"]
julia = "0.3-0.6"

["0.0.2-0.2"]
Distributions = "0.1-0.15"

["0.1"]
julia = "0.4-0.6"

["0.1.1"]
Plots = "0.0-0.15"

["0.1.1-0.2"]
ProgressMeter = "0.0-0.5"

["0.2"]
julia = "0.5-0.6"
