["0.1-0.2"]
julia = "0.4-0.6"

["0.1-0.3"]
Calculus = "0.1-0.2"
DataStructures = "0.2-0.7"
Distributions = "0.1-0.14"
HDF5 = "0.1-0.8"
QuantEcon = "0.0-0.13"
Roots = "0.1-0.4"

["0.1.0-0.1.1"]
Optim = "0.1-0.4"

["0.1.2-0.1.3"]
Optim = "0.5"

["0.1.3-0.3"]
FredData = "0.1"

["0.1.4"]
Optim = "0.5-0.9"

["0.1.5-0.3"]
Optim = "0.7-0.9"

["0.2-0.3"]
DataFrames = "0.1-0.10"
JLD = "0.5-0.8"
StateSpaceRoutines = "0.0"

["0.3"]
julia = "0.5-0.6"
