["0.1"]
julia = "0.5-0.6"
Automa = "0.0-0.3"
BioSequences = "0.5-0.8"
BufferedStreams = "0.0-0.3"
Compat = "0.17-0.31"
IntervalTrees = "0.2-0.3"

["0.1-0.2"]
BGZFStreams = "0.0-0.1"
BioCore = "1.0-1.2"
BioSymbols = "1.0-1.2"
GenomicFeatures = "0.1-0.2"

["0.2"]
julia = "0.6"
Automa = "0.1-0.3"
BioSequences = "0.6-0.8"
BufferedStreams = "0.3"
IntervalTrees = "0.1-0.3"
