["0.1-1.0"]
julia = "0.6-0.7"
FileIO = "0.5.1-0.7"

["0.1.0"]
DataFrames = "0.10"
IterableTables = "0.4.2"

["0.1.1-0.1.2"]
DataFrames = "0.9.1-0.10"
IterableTables = "0.4.2-0.7"

["1.0"]
DataFrames = "0.9-0.10"
IterableTables = "0.5-0.7"
TableTraits = "0.0-0.1"
