["0.1-0.6"]
julia = "0.6"
ForwardDiff = "0.5-0.7"
LsqFit = "0.3"
OrdinaryDiffEq = "2.17-2.31"
RecursiveArrayTools = "0.12-0.13"
Requires = "0.4.3"
StaticArrays = "0.5-0.6"
StatsBase = "0.8.2-0.19"

["0.2-0.6"]
IterTools = "0.1"
NearestNeighbors = "0.1-0.3"

["0.3-0.6"]
Distances = "0.1-0.5"

["0.4-0.6"]
Combinatorics = "0.0-0.5"
