["0.1-0.2"]
julia = "0.6"
ForwardDiff = "0.5"
LsqFit = "0.3"
OrdinaryDiffEq = "2.17-2.18"
RecursiveArrayTools = "0.12"
Requires = "0.4.3"
StaticArrays = "0.5-0.6"
StatsBase = "0.8.2-0.18"

["0.2"]
IterTools = "0.1"
NearestNeighbors = "0.1-0.3"
