["0.0-0.1.1"]
RecursiveArrayTools = "0.0-0.3"

["0.0-1.9"]
julia = "0.5-0.6"

["0.0-1.23"]
RecipesBase = "0.1-0.2"

["0.0.2-1.9"]
Ranges = "0.0"

["0.1.0-0.1.1"]
Parameters = "0.0-0.8"

["0.1.2-0.7"]
RecursiveArrayTools = "0.0.2-0.3"

["0.1.2-1.8"]
Parameters = "0.5-0.8"

["0.3-1.23"]
SimpleTraits = "0.1.1-0.5"

["0.8-0.15"]
RecursiveArrayTools = "0.2-0.3"

["0.12-1.23"]
Compat = "0.19-0.33"

["1.0-1.7"]
RecursiveArrayTools = "0.4-0.12"

["1.1-1.7"]
Iterators = "0.1-0.3"

["1.2-1.23"]
Juno = "0.1-0.3"

["1.7-1.9"]
StaticArrays = "0.0-0.6"

["1.8-1.9"]
RecursiveArrayTools = "0.8-0.12"

["1.10-1.23"]
julia = "0.6"

["1.10-1.23.0"]
RecursiveArrayTools = "0.9-0.12"

["1.11-1.23"]
LinearMaps = "0.0-1.0"

["1.23.1"]
RecursiveArrayTools = "0.12.3-0.12.4"
