["0.0-0.1"]
julia = "0.4-0.6"
Docile = "0.0-0.5"
FactCheck = "0.0-0.4"
HDF5 = "0.1-0.8"
Lexicon = "0.0-0.1"
LightXML = "0.1-0.5"

["0.0-0.3"]
DataFrames = "0.1-0.10"
Logging = "0.0-0.3"

["0.1"]
Lint = "0.0-0.5"

["0.1-0.3"]
ForwardDiff = "0.0-0.7"

["0.2"]
julia = "0.5-0.6"

["0.2-0.3"]
Formatting = "0.1-0.3"
HDF5 = "0.7-0.8"
LightXML = "0.4-0.5"

["0.3"]
julia = "0.6"
AbaqusReader = "0.1"
AsterReader = "0.1"
FEMQuad = "0.1"
TimerOutputs = "0.0-0.3"

["0.3.1-0.3.4"]
FEMBasis = "0.1"

["0.3.4"]
FEMBase = "0.0"
