["0.0"]
julia = "0.4-0.6"

["0.0-0.1"]
Plots = "0.0-0.12"

["0.0-0.2"]
RecipesBase = "0.0-0.2"
Reexport = "0.0"

["0.0.5-0.2"]
StatPlots = "0.0-0.5"

["0.1-0.2"]
julia = "0.5-0.6"

["0.2"]
NetworkLayout = "0.0-0.1"
Plots = "0.10-0.12"
