["0.0"]
PyCall = "1.4-1.14"

["0.0-0.1.0"]
SymDict = "0.0.2-0.1"

["0.0-0.2"]
julia = "0.4-0.6"

["0.0-0.3"]
Parameters = "0.3-0.7"

["0.0.1-0.0.3"]
ScikitLearnBase = "0.0-0.3"

["0.0.2-0.3"]
Conda = "0.1-0.7"
MacroTools = "0.3"

["0.0.3-0.2"]
Requires = "0.2-0.4"

["0.0.4"]
ScikitLearnBase = "0.0.4-0.3"

["0.0.4-0.3"]
StatsBase = "0.8-0.19"

["0.1-0.3"]
PyCall = "1.6.2-1.14"
ScikitLearnBase = "0.1-0.3"

["0.1.1-0.3"]
Iterators = "0.1.9-0.3"

["0.2"]
Compat = "0.9.2-0.31"

["0.3"]
julia = "0.5-0.6"
Compat = "0.18-0.31"
DataFrames = "0.1-0.10"
