["0.0"]
julia = "0.1-0.6"

["0.0-0.1"]
DataStructures = "0.2-0.7"
ImmutableArrays = "0.0"

["0.0.4"]
Lint = "0.0-0.5"

["0.1"]
julia = "0.3-0.6"
Compat = "0.0-0.31"
JSON = "0.1-0.14"
LightXML = "0.1-0.5"
ZipFile = "0.1-0.4"

["0.2"]
julia = "0.4-0.6"
FileIO = "0.0-0.5"
GeometryTypes = "0.0-0.4"
Meshing = "0.0-0.2"
MeshIO = "0.0-0.1"
