["0.5"]
julia = "0.5-0.6"

["0.5-0.6"]
AWSCore = "0.0-0.3"
AWSS3 = "0.0-0.3"
JSON = "0.1-0.16"
Memoize = "0.0-0.2"
Retry = "0.0-0.1"

["0.5-0.6.0"]
Libz = "0.0-0.2"

["0.6"]
julia = "0.6"
BigArrays = "0.5-0.6"
