["0.0"]
julia = "0.6"
Clustering = "0.9"
DataStructures = "0.5.3-0.7"
Distances = "0.1-0.5"
ImageFiltering = "0.1.4-0.2"
Images = "0.9-0.11"
LightGraphs = "0.9.2-0.11"
RegionTrees = "0.1"
SimpleWeightedGraphs = "0.0-0.3"
StaticArrays = "0.6"
