["0.0"]
julia = "0.4-0.7"
MacroTools = "0.2-0.4"

["0.1"]
julia = "0.5-0.7"
DataStructures = "0.2-0.7"
MacroTools = "0.1-0.4"

["0.1.0"]
NullableArrays = "0.0-0.1"

["0.1.3"]
Documenter = "0.1-0.13"
StructuredQueries = "0.0"
