["0.0-0.1"]
ImageTransformations = "0.1-0.4"

["0.0-0.2"]
julia = "0.5-0.6"
ColorTypes = "0.3.2-0.6"
Crayons = "0.1-0.3"
ImageCore = "0.1.1-0.4"

["0.1-0.2"]
Compat = "0.17-0.31"

["0.2"]
ImageTransformations = "0.2.1-0.4"
