["0.0"]
EzXML = "0.3-0.5"
GZip = "0.2.20-0.3"
JLD = "0.6.3-0.8"
LightGraphs = "0.8-0.11"
ParserCombinator = "1.7.11"

["0.0-0.1"]
julia = "0.6-0.7"

["0.1"]
EzXML = "0.0-0.5"
GZip = "0.1-0.3"
JLD = "0.5-0.8"
LightGraphs = "0.9-0.11"
ParserCombinator = "0.0-1.7"
SimpleTraits = "0.1-0.5"
