["0.0.1"]
julia = "0.1-0.6"

["0.0.2-0.0.4"]
julia = "0.3-0.6"
Compat = "0.0-0.37"
GeoInterface = "0.0-0.3"

["0.0.3-0.2"]
BinDeps = "0.0-0.6"
Homebrew = "0.0-0.6"
WinRPM = "0.1-0.3"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8.7-0.37"
GeoInterface = "0.1-0.3"

["0.2"]
julia = "0.5-0.6"
GeoInterface = "0.2.1-0.3"
