["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.37"
FixedPointNumbers = "0.0-0.2"

["0.0-0.1"]
Images = "0.2-0.5"

["0.0-0.2"]
FileIO = "0.0-0.6"

["0.1"]
julia = "0.4-0.6"

["0.1.0"]
FixedPointNumbers = "0.1-0.2"

["0.1.1"]
FixedPointNumbers = "0.1.8-0.2"

["0.2"]
julia = "0.5-0.6"
ColorVectorSpace = "0.0-0.5"
FixedPointNumbers = "0.3-0.4"
ImageCore = "0.0-0.5"

["0.2.0"]
Colors = "0.4-0.8"

["0.2.1"]
ColorTypes = "0.0-0.6"
