["0.0"]
julia = "0.6"
DataStreams = "0.3.1"
DocStringExtensions = "0.1-0.4"
Memento = "0.3"
Missings = "0.2.1-0.2.3"

["0.0.1"]
Compat = "0.26-0.39"

["0.0.2"]
BinDeps = "0.6-0.8"
Compat = "0.33-0.39"
