["0.1-0.2"]
CUDAdrv = "0.2-0.4"

["0.1-0.5"]
julia = "0.6"

["0.1.0"]
LLVM = "0.2"

["0.1.1"]
LLVM = "0.2-0.3.0"

["0.1.2-0.3.0"]
LLVM = "0.2-0.3.9"

["0.3.0"]
CUDAdrv = "0.4"

["0.3.1"]
CUDAdrv = "0.4.2"
LLVM = "0.3.5-0.3.9"

["0.4-0.5.0"]
CUDAdrv = "0.5.0-0.5.2"
LLVM = "0.3.8-0.3.9"

["0.5.1"]
CUDAapi = "0.1"
CUDAdrv = "0.5"
LLVM = "0.3.11-0.4"
