["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.39"
Dates = "0.0-0.4"

["0.0-0.2"]
DataFrames = "0.1-0.10"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8-0.39"

["0.1-0.2"]
ConfParser = "0.0"

["0.2"]
julia = "0.5-0.6"
Compat = "0.17-0.39"
