["0.0"]
julia = "0.5-0.6"
Codecs = "0.1-0.4"
Compat = "0.17-0.37"
DataTables = "0.0"
Documenter = "0.1-0.12"
Interpolations = "0.0-0.7"
LightXML = "0.1-0.5"
OffsetArrays = "0.1-0.4"
QuadGK = "0.1"
WriteVTK = "0.0-0.6"
