["0.0"]
julia = "0.5-0.7"
Codecs = "0.1-0.4"
Compat = "0.17-0.52"
DataTables = "0.0"
Documenter = "0.1-0.13"
Interpolations = "0.0-0.7"
LightXML = "0.1-0.5"
OffsetArrays = "0.1-0.5"
QuadGK = "0.1-0.2"
WriteVTK = "0.0-0.6"
