["0.0"]
NLsolve = "0.1-0.11"

["0.0-0.3"]
julia = "0.4"
IterativeSolvers = "0.0-0.4"
Plots = "0.0-0.12"

["0.0.1"]
Atom = "0.1-0.6"

["0.0.1-0.0.2"]
LaTeXStrings = "0.1-0.2"
PyPlot = "1.0-2.3"

["0.0.2-0.3"]
Parameters = "0.0-0.7"

["0.0.3"]
ForwardDiff = "0.0-0.5"
JLD = "0.5-0.8"

["0.0.3-0.3"]
ChunkedArrays = "0.0-0.1"
EllipsisNotation = "0.0-0.2"
GrowableArrays = "0.0"

["0.1.2-0.3"]
GenericSVD = "0.0-0.1"

["0.1.4-0.3"]
ForwardDiff = "0.0-0.5"

["0.3"]
Compat = "0.0-0.31"
InplaceOps = "0.0-0.1"

["0.4"]
SIUnits = "0.0.6-0.1"

["0.4-0.5"]
ChunkedArrays = "0.0.2-0.1"
Compat = "0.8.8-0.31"
ForwardDiff = "0.2.4-0.5"
GenericSVD = "0.0.2-0.1"
InplaceOps = "0.0.5-0.1"
IterativeSolvers = "0.2.2-0.4"
Plots = "0.9.2-0.12"

["0.4-1.0"]
DiffEqBase = "0.0-0.14"
OrdinaryDiffEq = "0.0-1.1"
StochasticDiffEq = "0.0-0.5"

["0.4-2.2"]
julia = "0.5-0.6"

["0.4.0"]
Parameters = "0.3.1-0.7"

["0.4.1-0.5"]
Parameters = "0.5-0.7"

["0.5"]
NLsolve = "0.7.3-0.11"
Ranges = "0.0"
Sundials = "0.3-0.14"

["1.0"]
AlgebraicDiffEq = "0.0-0.1"
DiffEqDevTools = "0.0-0.9"
DiffEqParamEstim = "0.0-0.6"
DiffEqSensitivity = "0.0-0.3"
FiniteElementDiffEq = "0.0-0.4"
Reexport = "0.0"
StokesDiffEq = "0.0-0.2"
Sundials = "0.1-0.14"

["1.1"]
DiffEqBase = "0.1.3-0.14"
DiffEqDevTools = "0.1.1-0.9"
OrdinaryDiffEq = "0.1.1-1.1"
StochasticDiffEq = "0.0.5-0.5"
Sundials = "0.3-0.14"

["1.1-1.10"]
AlgebraicDiffEq = "0.0.2-0.1"
DiffEqParamEstim = "0.0.2-0.6"
DiffEqSensitivity = "0.0.2-0.3"
FiniteElementDiffEq = "0.0.5-0.4"
ParameterizedFunctions = "0.3.2-2.2"
StokesDiffEq = "0.0.2-0.2"

["1.1-2.2"]
Reexport = "0.0.3"

["1.2-1.4"]
DiffEqProblemLibrary = "0.2-0.10"

["1.2-1.6"]
DiffEqBase = "0.2-0.14"
OrdinaryDiffEq = "0.2-1.1"
StochasticDiffEq = "0.1-0.5"

["1.2-1.10"]
DiffEqDevTools = "0.2-0.9"
Sundials = "0.5-0.14"

["1.5-1.10"]
DiffEqPDEBase = "0.0-0.3"

["1.6"]
DelayDiffEq = "0.0-0.10"

["1.6-1.10"]
DiffEqCallbacks = "0.0-0.3"
DiffEqMonteCarlo = "0.0-0.9"

["1.7-1.9"]
DiffEqBase = "0.8-0.14"

["1.7-1.10"]
DelayDiffEq = "0.1-0.10"
OrdinaryDiffEq = "1.2-2.18"
StochasticDiffEq = "1.0-2.11"

["1.8-1.10"]
DiffEqFinancial = "0.0-0.3"
DiffEqJump = "0.0-0.5"
MultiScaleArrays = "0.0-0.4"

["1.8-2.2"]
DiffEqBiological = "0.0-0.2"

["1.9.0"]
PyDSTool = "0.0-0.1"

["1.10"]
DiffEqBase = "0.15-1.22"

["2.0-2.1"]
ParameterizedFunctions = "1.3-2.2"
PyDSTool = "0.1.2"

["2.0-2.2"]
AlgebraicDiffEq = "0.1"
DelayDiffEq = "0.3-0.10"
DiffEqBase = "1.0-1.22"
DiffEqCallbacks = "0.0.2-0.3"
DiffEqDevTools = "0.8-0.9"
DiffEqFinancial = "0.2-0.3"
DiffEqJump = "0.3-0.5"
DiffEqMonteCarlo = "0.3-0.9"
DiffEqNoiseProcess = "0.0-0.5"
DiffEqParamEstim = "0.3-0.6"
DiffEqPDEBase = "0.3"
DiffEqSensitivity = "0.2-0.3"
DimensionalPlotRecipes = "0.0.2"
FiniteElementDiffEq = "0.3-0.4"
MultiScaleArrays = "0.1-0.4"
OrdinaryDiffEq = "2.0-2.18"
RecursiveArrayTools = "0.4.1-0.12"
SteadyStateDiffEq = "0.0-0.1"
StochasticDiffEq = "2.0-2.11"
Sundials = "0.11-0.14"

["2.1-2.2"]
DiffEqUncertainty = "0.0"

["2.2"]
ParameterizedFunctions = "2.0-2.2"
