["0.0"]
julia = "0.6"
BufferedStreams = "0.3"
Compat = "0.0-0.31"
Documenter = "0.1-0.11"
Libz = "0.2"

["0.0.6"]
StringEncodings = "0.1-0.2"

["0.0.6-0.0.7"]
LabelNumerals = "0.0"
TimeZones = "0.0-0.4"

["0.0.7"]
AdobeGlyphList = "0.0"
IntervalTrees = "0.0-0.3"
