["0.0"]
julia = "0.6"
BufferedStreams = "0.3"
Compat = "0.0-0.44"
Documenter = "0.1-0.12"
Libz = "0.2"

["0.0.6"]
StringEncodings = "0.1-0.2"

["0.0.6-0.0.9"]
LabelNumerals = "0.0"
TimeZones = "0.0-0.5"

["0.0.7-0.0.9"]
AdobeGlyphList = "0.0"
IntervalTrees = "0.0-0.4"

["0.0.8-0.0.9"]
DataStructures = "0.2-0.7"
