["0.1"]
julia = "0.3-0.6"

["0.1-0.4"]
GZip = "0.1-0.3"

["0.1-0.4.0"]
DataFrames = "0.1-0.10"

["0.2"]
julia = "0.4-0.6"

["0.3"]
julia = "0.5-0.6"
Compat = "0.0-0.39"

["0.4"]
julia = "0.6"

["0.4.1"]
DataFrames = "0.11"
