["0.0"]
julia = "0.6"
BinaryProvider = "0.1"
Compat = "0.27-0.44"
GitHub = "0.0-3.1"
HTTP = "0.0-0.5"
JSON = "0.1-0.16"
MbedTLS = "0.1-0.5"
ObjectFile = "0.1"
PkgDev = "0.1"
ProgressMeter = "0.0-0.5"
Reexport = "0.0-0.1"
TerminalMenus = "0.0"
