["0.0"]
julia = "0.5-0.6"
StaticArrays = "0.0-0.6"
Sugar = "0.0-0.3"

["0.0-0.2"]
OpenCL = "0.5.2-0.6"

["0.0-0.3"]
Compat = "0.17-0.31"
DataStructures = "0.2-0.6"
Matcha = "0.0-0.1"
SpecialFunctions = "0.0-0.3"

["0.1-0.3"]
julia = "0.6"
StaticArrays = "0.3-0.6"
Sugar = "0.3"

["0.3"]
MacroTools = "0.1-0.3"
