["0.0.1-0.0.2"]
julia = "0.4"

["0.0.1-0.0.4"]
Libz = "0.0-0.2"

["0.0.1-0.0.5"]
Compat = "0.0-0.53"
DataStreams = "0.0.1-0.0.4"

["0.0.1-0.0.9"]
NullableArrays = "0.0-0.1"

["0.0.3-0.0.5"]
julia = "0.4.1-0.4.7"

["0.0.6-0.0.9"]
DataStreams = "0.0.5-0.0.6"
WeakRefStrings = "0.1-0.2"

["0.0.6-0.0.14"]
julia = "0.4.1-0.7"

["0.0.6-0.1"]
DataFrames = "0.1-0.10"

["0.0.11"]
DataStreams = "0.0.8-0.0.12"
WeakRefStrings = "0.1.2-0.2"

["0.0.12"]
DataStreams = "0.0.10-0.0.12"

["0.0.12-0.1"]
WeakRefStrings = "0.1.3-0.2"

["0.0.13"]
DataStreams = "0.0.12"

["0.0.14"]
DataStreams = "0.0.13-0.1"

["0.1"]
julia = "0.5-0.7"
DataStreams = "0.1"

["0.1.4-0.1.5"]
Compat = "0.9.5-0.53"

["0.2"]
julia = "0.6-0.7"
CategoricalArrays = "0.3"
DataFrames = "0.11"
DataStreams = "0.3"
WeakRefStrings = "0.4"

["0.2.0"]
Mmap = "0.7"

["0.2.1"]
Compat = "0.41-0.53"
Dates = "0.7"
Test = "0.7"
