["0.0"]
julia = "0.4-0.7"
DataFrames = "0.1-0.10"

["0.0-0.1"]
Logging = "0.7"
Thrift = "0.0-0.4"

["0.0.3"]
Compat = "0.8-0.53"

["0.1"]
julia = "0.6-0.7"
Compat = "0.27-0.53"
DataArrays = "0.0-0.7"
DataFrames = "0.1-0.11"
