["0.0"]
GLAbstraction = "0.0-0.5"
GLFW = "0.0-1.4"
GLWindow = "0.0-0.7"
Images = "0.2-0.11"
ImmutableArrays = "0.0"
ModernGL = "0.0-0.2"
Mustache = "0.0-0.3"

["0.0.1"]
React = "0.1"

["0.0.1-0.0.2"]
julia = "0.1-0.6"

["0.0.2-0.0.5"]
GLText = "0.0"
Reactive = "0.1-0.6"

["0.0.3-0.0.5"]
julia = "0.3-0.6"
Quaternions = "0.0-0.3"

["0.0.4-0.0.5"]
Compat = "0.0-0.33"

["0.0.5"]
Color = "0.1-0.4"
FixedPointNumbers = "0.0-0.4"
