["0.0"]
DiffEqBase = "0.0-0.7"

["0.0-0.5"]
ChunkedArrays = "0.1"

["0.0-2.2"]
julia = "0.5-0.6"
ForwardDiff = "0.0-0.4"

["0.0-2.19"]
Parameters = "0.5-0.8"

["0.0.1-0.0.4"]
ParameterizedFunctions = "0.1-2.3"

["0.0.4-0.0.5"]
RecursiveArrayTools = "0.0-0.12"

["0.1-0.3"]
DiffEqBase = "0.2-0.7"
RecursiveArrayTools = "0.0.2-0.12"

["0.3"]
DataStructures = "0.2-0.7"
Juno = "0.1-0.3"

["0.3-1.4"]
ResettableStacks = "0.0-0.2"

["0.4-0.5"]
DiffEqBase = "0.4-0.7"
RecursiveArrayTools = "0.1.2-0.12"

["0.4-2.19"]
DataStructures = "0.4.6-0.7"
Juno = "0.2.5-0.3"

["1.0"]
DiffEqBase = "0.8-0.14"

["1.0-2.2"]
Iterators = "0.1-0.3"
RecursiveArrayTools = "0.2-0.12"

["1.0-2.19"]
Roots = "0.1-0.4"

["1.1-1.2"]
DiffEqBase = "0.11-0.14"

["1.2-2.19"]
Compat = "0.17-0.37"

["1.3"]
DiffEqBase = "0.13-0.14"

["1.4"]
DiffEqBase = "0.15"

["2.0-2.5"]
DiffEqNoiseProcess = "0.0-0.7"

["2.0-2.19"]
NLsolve = "0.1-0.13"

["2.0.0-2.0.1"]
DiffEqBase = "1.1-1.14"

["2.0.2-2.3"]
DiffEqBase = "1.2-1.14"

["2.2-2.19"]
StaticArrays = "0.0-0.6"

["2.3-2.11"]
ForwardDiff = "0.5"

["2.3-2.19"]
julia = "0.6"
RecursiveArrayTools = "0.8-0.12"

["2.4-2.6"]
DiffEqBase = "1.10-1.14"

["2.5-2.19"]
Reexport = "0.0"

["2.6"]
DiffEqNoiseProcess = "0.2-0.7"

["2.7"]
DiffEqBase = "1.13-1.14"

["2.7-2.11.0"]
DiffEqNoiseProcess = "0.3-0.7"

["2.7-2.19"]
RandomNumbers = "0.0-0.1"

["2.8-2.9"]
DiffEqBase = "1.15"

["2.10-2.11"]
DiffEqBase = "1.16-1.24"

["2.10-2.19"]
MuladdMacro = "0.0"

["2.11.1-2.19"]
DiffEqNoiseProcess = "0.5-0.7"

["2.12"]
DiffEqBase = "1.24"

["2.12-2.16"]
ForwardDiff = "0.5-0.7"

["2.13-2.15"]
DiffEqBase = "2.0-2.6"

["2.16-2.17"]
DiffEqDiffTools = "0.1"

["2.16-2.18"]
DiffEqBase = "2.4-2.6"

["2.17-2.19"]
ForwardDiff = "0.7"

["2.18-2.19"]
DiffEqDiffTools = "0.2"

["2.19"]
DiffEqBase = "2.6"
