["0.0"]
DiffEqBase = "0.0-0.7"

["0.0-0.5"]
ChunkedArrays = "0.1"

["0.0-2.2"]
julia = "0.5-0.6"

["0.0-2.11"]
Parameters = "0.5-0.7"

["0.0.1-0.0.4"]
ParameterizedFunctions = "0.1-2.2"

["0.0.4-0.0.5"]
RecursiveArrayTools = "0.0-0.12"

["0.1-0.3"]
DiffEqBase = "0.2-0.7"
RecursiveArrayTools = "0.0.2-0.12"

["0.3"]
DataStructures = "0.2-0.7"
Juno = "0.1-0.3"

["0.3-1.4"]
ResettableStacks = "0.0-0.2"

["0.4-0.5"]
DiffEqBase = "0.4-0.7"
RecursiveArrayTools = "0.1.2-0.12"

["0.4-2.11"]
DataStructures = "0.4.6-0.7"
Juno = "0.2.5-0.3"

["1.0"]
DiffEqBase = "0.8-0.14"

["1.0-2.2"]
Iterators = "0.1-0.3"
RecursiveArrayTools = "0.2-0.12"

["1.0-2.11"]
Roots = "0.1-0.4"

["1.1-1.2"]
DiffEqBase = "0.11-0.14"

["1.2-2.11"]
Compat = "0.17-0.31"

["1.3"]
DiffEqBase = "0.13-0.14"

["1.4"]
DiffEqBase = "0.15"

["2.0-2.2"]
ForwardDiff = "0.0-0.5"

["2.0-2.5"]
DiffEqNoiseProcess = "0.0-0.5"

["2.0-2.11"]
NLsolve = "0.1-0.11"

["2.0.0-2.0.1"]
DiffEqBase = "1.1-1.14"

["2.0.2-2.3"]
DiffEqBase = "1.2-1.14"

["2.2-2.11"]
StaticArrays = "0.0-0.6"

["2.3-2.11"]
julia = "0.6"
ForwardDiff = "0.5"
RecursiveArrayTools = "0.8-0.12"

["2.4-2.6"]
DiffEqBase = "1.10-1.14"

["2.5-2.11"]
Reexport = "0.0"

["2.6"]
DiffEqNoiseProcess = "0.2-0.5"

["2.7"]
DiffEqBase = "1.13-1.14"

["2.7-2.11"]
DiffEqNoiseProcess = "0.3-0.5"
RandomNumbers = "0.0-0.1"

["2.8-2.9"]
DiffEqBase = "1.15"

["2.10-2.11"]
DiffEqBase = "1.16-1.22"
MuladdMacro = "0.0"
