["0.0"]
julia = "0.6"
DocStringExtensions = "0.1-0.4"
Documenter = "0.1-0.12"
ForwardDiff = "0.0-0.7"
Interpolations = "0.0-0.7"
MacroTools = "0.1-0.4"
MappedArrays = "0.0"
RecipesBase = "0.0-0.2"
Reexport = "0.0-0.1"

["0.0.2"]
PlotUtils = "0.0-0.4"
