["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.5"]
julia = "0.5-0.6"

["0.0.2"]
Compat = "0.0-0.39"

["0.1-0.2"]
DiffEqBase = "0.15-2.6"

["0.2-0.5"]
Compat = "0.17-0.39"

["0.3-0.5"]
DiffEqBase = "1.5.1-2.6"

["0.4-0.5"]
Reexport = "0.0"
