["0.0"]
DiffEqBase = "0.0-0.14"

["0.0-0.4"]
julia = "0.5-0.6"

["0.0.2"]
Compat = "0.0-0.33"

["0.1-0.2"]
DiffEqBase = "0.15-1.23"

["0.2-0.4"]
Compat = "0.17-0.33"

["0.3-0.4"]
DiffEqBase = "1.5.1-1.23"

["0.4"]
Reexport = "0.0"
