["0.0"]
julia = "0.2-0.6"

["0.0-0.1"]
Polynomial = "0.1"

["0.1"]
julia = "0.3-0.6"

["0.1.1-0.2.0"]
Compat = "0.0-0.39"

["0.2"]
julia = "0.4-0.6"

["0.2-0.4.0"]
Iterators = "0.1-0.3"

["0.2-0.5"]
Polynomials = "0.0-0.1"

["0.3-0.5"]
julia = "0.5-0.6"

["0.4-0.5"]
Compat = "0.18-0.39"

["0.4.1-0.5"]
IterTools = "0.1"
