["0.0-0.1"]
julia = "0.4"

["0.0-0.2"]
FixedSizeArrays = "0.0-0.2"
Quaternions = "0.0-0.3"

["0.2"]
julia = "0.4-0.5"
Compat = "0.0-0.31"

["0.3"]
julia = "0.5-0.6"

["0.3.0-0.3.4"]
StaticArrays = "0.0.3-0.2"

["0.3.5"]
StaticArrays = "0.3"

["0.4"]
StaticArrays = "0.4"

["0.4-0.6"]
julia = "0.6"

["0.5-0.6"]
StaticArrays = "0.5-0.6"
