["0.1"]
julia = "0.4-0.6"
Compat = "0.0-0.39"

["0.1.0"]
DistributedArrays = "0.1-0.4"

["0.1.1-0.1.2"]
DistributedArrays = "0.2-0.4"

["0.2"]
julia = "0.6"
Compat = "0.31-0.39"
DistributedArrays = "0.4"
