["0.0.1-0.0.3"]
julia = "0.2-0.6"

["0.0.4"]
julia = "0.3-0.6"

["0.1"]
julia = "0.4-0.6"

["0.1-0.3"]
FactCheck = "0.0-0.4"

["0.2-0.3"]
julia = "0.5-0.6"
DiffEqBase = "0.15-2.6"

["0.3"]
Reexport = "0.0"
