["0.0-0.1"]
Docile = "0.0-0.5"

["0.0-0.2"]
julia = "0.3-0.6"

["0.0-0.3"]
Compat = "0.0-0.31"
DataStructures = "0.2-0.6"

["0.3-0.5"]
julia = "0.4-0.6"

["0.4-0.5"]
Compat = "0.7.15-0.31"

["0.4-0.6"]
DataStructures = "0.4.3-0.6"

["0.6-0.7"]
julia = "0.5-0.6"

["0.7"]
DataStructures = "0.5.2-0.6"

["0.7.0-0.7.1"]
Compat = "0.17-0.31"
