["0.2"]
julia = "0.3-0.6"
Compat = "0.0-0.33"
Docile = "0.0-0.5"
FactCheck = "0.0-0.4"
Reexport = "0.0"

["0.2-0.6"]
Distributions = "0.1-0.14"
StatsBase = "0.1-0.19"
UnicodePlots = "0.0-0.2"

["0.3"]
Plots = "0.0-0.13"

["0.3-0.4"]
OnlineStats = "0.1-0.11"

["0.3-0.5"]
julia = "0.4-0.6"

["0.5.1"]
Requires = "0.1-0.4"

["0.5.2-0.6"]
RecipesBase = "0.0-0.2"

["0.6"]
julia = "0.6"
