["0.0"]
julia = "0.4-0.6"
Colors = "0.4-0.8"
FixedPointNumbers = "0.0-0.4"

["0.0.1"]
Compat = "0.0-0.31"

["0.0.2"]
Compat = "0.7.15-0.31"

["0.1"]
julia = "0.5-0.6"

["0.1-0.2"]
ColorTypes = "0.3.4-0.6"
Compat = "0.17-0.31"
FixedPointNumbers = "0.3-0.4"

["0.2"]
julia = "0.6"
