["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.31"

["0.0-0.1"]
Images = "0.2-0.5"
SIUnits = "0.0-0.1"

["0.0-0.5"]
FileIO = "0.0-0.5"

["0.1"]
julia = "0.4-0.6"

["0.1.2"]
Compat = "0.7.16-0.31"

["0.2-0.3"]
julia = "0.5-0.6"
Ranges = "0.0"

["0.2-0.5"]
AxisArrays = "0.0-0.1"
FixedPointNumbers = "0.3-0.4"
ImageMetadata = "0.1.1-0.3"
Unitful = "0.0-0.2"

["0.4-0.5"]
julia = "0.6"
