["0.0"]
julia = "0.5-0.6"
NamedTuples = "2.0-2.1"
Requires = "0.3-0.4"

["0.1-0.2"]
NamedTuples = "3.0.2-3.0.3"

["0.1-0.5"]
julia = "0.6"
DataValues = "0.0.3-0.2"
Requires = "0.4.3"

["0.3-0.5"]
NamedTuples = "4.0"

["0.5"]
TableTraits = "0.0"
