["0.1"]
julia = "0.4-0.7"

["0.1-0.4"]
BinDeps = "0.0-0.8"

["0.1.0-0.1.4"]
Compat = "0.0-0.53"

["0.1.5"]
Compat = "0.7.20-0.53"

["0.2-0.3"]
julia = "0.5-0.7"
Compat = "0.17-0.53"

["0.4"]
julia = "0.6-0.7"
Compat = "0.40-0.53"

["0.4.1"]
Printf = "0.7"
Test = "0.7"
Unicode = "0.7"
