["0.1"]
julia = "0.1-0.6"

["0.2-0.3"]
julia = "0.3-0.6"

["0.3.0-0.3.2"]
Compat = "0.4-0.31"

["0.3.3-0.3.14"]
Compat = "0.0-0.31"

["0.4"]
julia = "0.6"
DataStructures = "0.2-0.7"
TaylorSeries = "0.0-0.5"
