["0.1"]
julia = "0.6-0.7"
Clustering = "0.2-0.9"
Colors = "0.4-0.8"
Distances = "0.1-0.5"
RecipesBase = "0.0-0.3"

["0.1.0"]
DataFrames = "0.1-0.10"

["0.1.2"]
DataFrames = "0.1-0.11"
StatPlots = "0.0-0.7"
