["0.0"]
BinDeps = "0.0-0.6"
Compat = "0.0-0.31"
Images = "0.2-0.11"

["0.0.1-0.0.2"]
julia = "0.3"

["0.0.3-0.0.6"]
julia = "0.3-0.6"
FactCheck = "0.0-0.4"
TestImages = "0.0-0.2"

["0.0.4-0.0.6"]
Colors = "0.4-0.8"
