["0.0"]
DiffEqBase = "1.0-1.2"

["0.0-0.2"]
julia = "0.5-0.6"

["0.0-0.4"]
ResettableStacks = "0.0-0.2"

["0.0-0.7"]
DataStructures = "0.2-0.7"
RecipesBase = "0.0-0.2"
RecursiveArrayTools = "0.0-0.12"

["0.1-0.2"]
DiffEqBase = "1.3.1-2.6"

["0.3-0.7"]
julia = "0.6"
DiffEqBase = "1.13-2.6"
RandomNumbers = "0.0-0.1"

["0.5-0.7"]
ResettableStacks = "0.2"
