["0.1-0.2"]
julia = "0.5-0.6"

["0.1-0.5"]
Compat = "0.19-0.44"
Logging = "0.0-0.3"

["0.3-0.5"]
julia = "0.6"

["0.3.2"]
MemPool = "0.0"

["0.4"]
MemPool = "0.0.2-0.0.5"

["0.5"]
MemPool = "0.0.4-0.0.5"
StatsBase = "0.1-0.19"
