["0.1"]
julia = "0.4-0.6"

["0.1-0.7"]
JSON = "0.1-0.16"

["0.2.0-0.2.1"]
julia = "0.3-0.6"

["0.2.2-0.3.1"]
julia = "0.4-0.6"

["0.3-0.7"]
ColorBrewer = "0.1-0.3"

["0.3.2-0.5"]
julia = "0.3-0.6"

["0.3.3-0.5"]
Compat = "0.0-0.44"

["0.5.2-0.7"]
KernelDensity = "0.0-0.4"

["0.6"]
julia = "0.4-0.6"

["0.6-0.7"]
NoveltyColors = "0.0-0.3"

["0.6.4-0.7"]
Patchwork = "0.1-0.4"

["0.7"]
julia = "0.5-0.6"
StatsBase = "0.1-0.19"
