["0.1-0.4"]
BinDeps = "0.0-0.6"

["0.1.0"]
julia = "0.3-0.6"

["0.1.1-0.1.2"]
julia = "0.3"

["0.2"]
julia = "0.4-0.6"

["0.2.0-0.2.1"]
Compat = "0.0-0.31"

["0.2.2"]
Compat = "0.8.8-0.31"

["0.3"]
julia = "0.5-0.6"
AbstractTrees = "0.0.4-0.1"

["0.4"]
julia = "0.6"
AbstractTrees = "0.1"
