["0.0"]
julia = "0.6"

["0.0.1-0.0.4"]
DataFrames = "0.1-0.10"

["0.0.1-0.0.5"]
GeoStatsBase = "0.0"

["0.0.2"]
Parameters = "0.0-0.8"

["0.0.3-0.0.6"]
Parameters = "0.7.3-0.8"

["0.0.5"]
DataFrames = "0.1-0.11"

["0.0.6"]
CSV = "0.2"
DataFrames = "0.11"
GeoStatsBase = "0.0.5"
