["0.0-0.1"]
Distributions = "0.1-0.14"
Reexport = "0.0"

["0.0.1"]
StatsBase = "0.1-0.18"

["0.0.1-0.0.3"]
julia = "0.3.6-0.6"
GLM = "0.2-0.7"

["0.0.2-0.0.4"]
StatsBase = "0.6.12-0.18"

["0.0.4"]
julia = "0.3.7-0.6"
Compat = "0.0-0.31"
GLM = "0.4.8-0.7"

["0.1"]
julia = "0.5-0.6"
GLM = "0.6.1-0.7"
MLBase = "0.1-0.7"
StatsBase = "0.8-0.18"
