["0.0-0.1.0"]
DiffEqBase = "0.0-0.4"
FiniteElementDiffEq = "0.0-0.4"
OrdinaryDiffEq = "0.0-3.0"
RecursiveArrayTools = "0.0-0.3"
StochasticDiffEq = "0.0-2.23"

["0.0-0.8"]
julia = "0.5-0.7"

["0.0-0.11"]
RecipesBase = "0.1-0.3"

["0.1.1"]
DiffEqBase = "0.1.3-0.4"
OrdinaryDiffEq = "0.1.1-3.0"
StochasticDiffEq = "0.0.5-2.23"

["0.1.1-0.2.0"]
FiniteElementDiffEq = "0.0.5-0.4"

["0.1.1-0.3"]
RecursiveArrayTools = "0.0.2-0.3"

["0.2.0"]
DiffEqBase = "0.2-0.4"

["0.2.1-0.3"]
DiffEqBase = "0.3-0.4"

["0.4-0.5"]
DiffEqBase = "0.4"

["0.4-0.7"]
RecursiveArrayTools = "0.1.2-0.3"

["0.5-0.11"]
DiffEqPDEBase = "0.0-0.3"

["0.6"]
DiffEqBase = "0.5-0.14"

["0.7"]
DiffEqBase = "0.15"

["0.8"]
DiffEqBase = "1.0-2.10"

["0.8-0.11"]
RecursiveArrayTools = "0.4-0.14"

["0.9-0.11"]
julia = "0.6-0.7"
DiffEqBase = "1.12-2.10"
DiffEqMonteCarlo = "0.0-0.9"
DiffEqNoiseProcess = "0.0-0.8"

["0.10-0.11"]
Juno = "0.1-0.3"
