["0.0"]
julia = "0.5-0.6"
Colors = "0.4-0.8"
Distributions = "0.1-0.15"
HDF5 = "0.1-0.8"
JLD = "0.5-0.8"

["0.0.1-0.0.3"]
Graphs = "0.2-0.8"
IncrementalInference = "0.0-0.2"
KernelDensityEstimate = "0.0-0.2"
TransformUtils = "0.0"

["0.0.1-0.0.6"]
Gadfly = "0.1-0.6"

["0.0.4"]
IncrementalInference = "0.2.5-0.2.11"

["0.0.4-0.0.5"]
KernelDensityEstimate = "0.2.3-0.2.6"
TransformUtils = "0.0.5-0.0.7"

["0.0.4-0.0.7"]
Graphs = "0.7.1-0.8"

["0.0.4-0.0.8"]
Optim = "0.1-0.10"

["0.0.5"]
IncrementalInference = "0.2.7-0.2.11"

["0.0.5-0.0.8"]
ProgressMeter = "0.0-0.5"

["0.0.6-0.0.7"]
IncrementalInference = "0.2.8-0.2.11"
KernelDensityEstimate = "0.2.4-0.2.6"

["0.0.6-0.0.8"]
CoordinateTransformations = "0.1-0.4"
Rotations = "0.0-0.6"
TransformUtils = "0.0.6-0.0.7"

["0.0.7-0.0.8"]
Gadfly = "0.6.2-0.6.4"

["0.0.8"]
Graphs = "0.8"
IncrementalInference = "0.2.10-0.2.11"
KernelDensityEstimate = "0.2.6"
