["0.0"]
BufferedStreams = "0.0-0.3"

["0.0-0.2"]
julia = "0.4-0.6"

["0.1"]
Compat = "0.0-0.37"

["0.1.0"]
BufferedStreams = "0.1-0.3"

["0.1.1-0.2.0"]
BufferedStreams = "0.1.1-0.3"

["0.2.0-0.2.1"]
Compat = "0.8-0.37"

["0.2.1"]
BufferedStreams = "0.2-0.3"

["0.2.2-0.2.3"]
Compat = "0.9.5-0.37"

["0.2.2-0.2.4"]
BufferedStreams = "0.2.1-0.3"

["0.2.4"]
Compat = "0.17-0.37"
