["0.2"]
Distributions = "0.2-0.15"

["0.2.0"]
NumericExtensions = "0.2.12-0.6"

["0.2.0-0.2.2"]
julia = "0.2-0.6"
DataFrames = "0.3.6-0.10"
StatsBase = "0.1-0.8.2"

["0.2.1-0.2.5"]
NumericExtensions = "0.2.17-0.6"

["0.2.3"]
StatsBase = "0.3-0.8.2"

["0.2.3-0.2.5"]
julia = "0.2"
DataFrames = "0.3.6-0.5.0"

["0.2.4-0.2.5"]
StatsBase = "0.2.10-0.8.2"

["0.3"]
DataFrames = "0.5-0.10"
StatsBase = "0.3.7-0.8.2"

["0.3-0.4"]
julia = "0.3-0.6"

["0.3-0.5"]
Distributions = "0.6-0.15"

["0.3.0"]
NumericExtensions = "0.5-0.6"

["0.3.1-0.4.2"]
NumericExtensions = "0.6"

["0.3.1-0.4.7"]
NumericFuns = "0.2.1-0.2.4"

["0.4.0-0.4.6"]
StatsBase = "0.3.10-0.8.2"

["0.4.3-0.5"]
Compat = "0.2.12-0.37"

["0.4.3-0.8"]
Reexport = "0.0"

["0.4.7-0.5.1"]
StatsBase = "0.7.1-0.8.2"

["0.5.0-0.5.5"]
julia = "0.4-0.6"

["0.5.2-0.5.3"]
StatsBase = "0.8.0-0.8.2"

["0.5.4-0.5.5"]
StatsBase = "0.8.3-0.19"

["0.5.5-0.8"]
StatsFuns = "0.3-0.5"

["0.5.6"]
julia = "0.4-0.5"

["0.5.6-0.6"]
StatsBase = "0.11-0.19"

["0.6-0.7"]
julia = "0.5-0.6"

["0.6-0.8"]
Distributions = "0.10-0.15"

["0.7-0.8"]
Compat = "0.18-0.37"
StatsBase = "0.12-0.19"

["0.8"]
julia = "0.6"
SpecialFunctions = "0.1-0.3"
