["0.5"]
PairwiseListMatrices = "0.0-0.6"

["0.5-0.6"]
julia = "0.5-0.6"

["0.5-0.6.2"]
Iterators = "0.1-0.3"

["0.5-0.8"]
Automa = "0.0-0.4"
BioCore = "1.0-1.2"
BioSymbols = "1.0-1.2"
BufferedStreams = "0.0-0.3"
Combinatorics = "0.0-0.5"
DataStructures = "0.2-0.7"
IndexableBitVectors = "0.0-0.1"
IntervalTrees = "0.0-0.4"
Twiddle = "0.1-0.4"

["0.6"]
Compat = "0.18-0.44"

["0.6.3-0.8"]
IterTools = "0.1-0.2"

["0.7-0.8"]
julia = "0.6"
