["0.0"]
julia = "0.4-0.6"
Ipopt = "0.1-0.2"

["0.0-0.1"]
ODE = "0.1-0.7"

["0.0-0.2"]
MathProgBase = "0.1-0.6"

["0.1"]
julia = "0.5-0.6"

["0.2"]
julia = "0.6"
DiffEqBase = "0.0-1.23"
Ipopt = "0.1-0.2"
OrdinaryDiffEq = "0.0-2.19"
