["0.0"]
julia = "0.3-0.6"
Distributions = "0.1-0.14"
Docile = "0.0-0.5"
DualNumbers = "0.0-0.3"
ForwardDiff = "0.0-0.5"
JuMP = "0.1-0.18"
MathProgBase = "0.1-0.6"
NLsolve = "0.1-0.11"
Optim = "0.1-0.4"
ReverseDiffSparse = "0.0-0.8"
