["0.0"]
julia = "0.3-0.6"
Distributions = "0.1-0.15"
Docile = "0.0-0.5"
DualNumbers = "0.0-0.3"
ForwardDiff = "0.0-0.7"
JuMP = "0.1-0.18"
MathProgBase = "0.1-0.7"
NLsolve = "0.1-0.13"
Optim = "0.1-0.4"
ReverseDiffSparse = "0.0-0.8"
