["0.2.0"]
MLBase = "0.1-0.7"

["0.2.0-0.2.2"]
Devectorize = "0.2-0.4"

["0.2.0-0.2.5"]
julia = "0.2-0.6"
Distance = "0.2-0.5"

["0.2.1-0.2.4"]
StatsBase = "0.1-0.19"

["0.2.3-0.2.5"]
NumericExtensions = "0.2-0.6"

["0.2.5-0.3.2"]
StatsBase = "0.3-0.19"

["0.2.6-0.3.1"]
Distance = "0.4-0.5"

["0.2.6-0.3.2"]
ArrayViews = "0.3-0.6"

["0.2.6-0.5"]
julia = "0.3-0.6"

["0.3.2"]
Distances = "0.1-0.5"

["0.3.3-0.4"]
ArrayViews = "0.4.8-0.6"
StatsBase = "0.6.9-0.19"

["0.3.3-0.5"]
Distances = "0.2-0.5"

["0.5"]
ArrayViews = "0.6"
Compat = "0.0-0.33"
StatsBase = "0.7-0.19"

["0.6-0.7"]
julia = "0.4-0.6"
Compat = "0.8.5-0.33"

["0.6-0.9"]
Distances = "0.3.1-0.5"
StatsBase = "0.9-0.19"

["0.7-0.9"]
NearestNeighbors = "0.0.3-0.3"

["0.8-0.9"]
julia = "0.5-0.6"
Compat = "0.17-0.33"
