["0.0-0.1.0"]
WoodburyMatrices = "0.0-0.2"

["0.0-0.3"]
julia = "0.4-0.6"

["0.1.1-0.3.4"]
WoodburyMatrices = "0.1-0.2"

["0.1.1-0.6"]
AxisAlgorithms = "0.1-0.2"
Ratios = "0.0-0.1"

["0.3.5-0.6"]
WoodburyMatrices = "0.1.5-0.2"

["0.3.6-0.3.7"]
Compat = "0.8-0.31"

["0.3.7-0.6"]
DualNumbers = "0.0-0.3"

["0.3.8-0.6"]
Compat = "0.19-0.31"

["0.4-0.6"]
julia = "0.5-0.6"

["0.5-0.6"]
ShowItLikeYouBuildIt = "0.0-0.1"
