["0.0-0.2"]
julia = "0.4-0.7"
JSON = "0.1-0.5"

["0.0-0.4"]
HttpServer = "0.0-0.2"
Requests = "0.0-0.5"
URIParser = "0.0-0.3"

["0.3"]
julia = "0.5-0.7"

["0.3-0.4"]
JSON = "0.1-0.16"

["0.4"]
julia = "0.6-0.7"
