["0.0"]
Datetime = "0.1"

["0.0-0.2.6"]
julia = "0.3-0.7"
TimeSeries = "0.0-0.11"

["0.1"]
HDF5 = "0.1-0.8"

["0.1-0.2.0"]
Reexport = "0.0-0.1"

["0.2.0-0.2.6"]
Dates = "0.0-0.4"

["0.2.7-0.3.0"]
julia = "0.3"
TimeSeries = "0.5.11"

["0.3.1-0.3.6"]
julia = "0.4"
TimeSeries = "0.6-0.11"

["0.3.7"]
TimeSeries = "0.8-0.11"

["0.3.7-0.4"]
julia = "0.4-0.7"

["0.3.8"]
TimeSeries = "0.6-0.11"

["0.4"]
TimeSeries = "0.8-0.11"

["0.5-0.6"]
julia = "0.5-0.7"
TimeSeries = "0.9-0.11"

["0.6"]
Requests = "0.0-0.5"
