["0.7"]
julia = "0.4"

["0.8"]
julia = "0.4-0.6"

["0.8.0"]
AutoGrad = "0.0.3-0.0.9"

["0.8.1"]
AutoGrad = "0.0.4-0.0.9"

["0.8.2"]
AutoGrad = "0.0.6-0.0.9"

["0.8.2-0.8.4"]
Compat = "0.16-0.37"

["0.8.3"]
AutoGrad = "0.0.7-0.0.9"

["0.8.4"]
AutoGrad = "0.0.8-0.0.9"

["0.8.5"]
AutoGrad = "0.0.9"
