["0.0-0.2"]
julia = "0.1-0.6"

["0.0-0.3"]
Compat = "0.0-0.31"
Docile = "0.0-0.5"

["0.0-0.5.0"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"

["0.1.2-0.3.1"]
BinDeps = "0.0-0.6"

["0.3"]
julia = "0.3-0.6"

["0.4-0.5"]
julia = "0.4-0.6"

["0.4.1-0.5"]
WinReg = "0.1-0.2"

["0.5"]
DataStructures = "0.2-0.6"

["0.5.0"]
Compat = "0.0-0.31"

["0.5.1-0.5.2"]
DataArrays = "0.3.8-0.6"
DataFrames = "0.7.6-0.10"

["0.5.1-0.6"]
Compat = "0.8-0.31"

["0.6"]
CategoricalArrays = "0.0.6-0.1"
DataFrames = "0.8.4-0.10"
DataStructures = "0.4.3-0.6"
NullableArrays = "0.0.10-0.1"

["0.6-0.7"]
julia = "0.5-0.6"
WinReg = "0.2"

["0.7"]
AxisArrays = "0.0.6-0.1"
CategoricalArrays = "0.1"
Compat = "0.17-0.31"
DataFrames = "0.9-0.10"
DataStructures = "0.5-0.6"
NamedArrays = "0.5.3-0.6"
NullableArrays = "0.1"
