["0.0-0.2"]
julia = "0.1-0.5"

["0.0-0.3"]
Compat = "0.0-0.37"
Docile = "0.0-0.5"

["0.0-0.5.0"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"

["0.1.2-0.3.1"]
BinDeps = "0.0-0.6"

["0.3"]
julia = "0.3-0.5"

["0.4"]
julia = "0.4-0.5"

["0.4.1-0.5"]
WinReg = "0.1-0.2"

["0.5"]
julia = "0.4-0.6"
CategoricalArrays = "0.0-0.1"
DataStructures = "0.2-0.7"

["0.5.0"]
Compat = "0.0-0.37"

["0.5.1-0.5.2"]
DataArrays = "0.3.8-0.6"
DataFrames = "0.7.6-0.10"

["0.5.1-0.6"]
Compat = "0.8-0.37"

["0.6"]
CategoricalArrays = "0.0.6-0.1"
DataFrames = "0.8.4-0.10"
DataStructures = "0.4.3-0.7"
NullableArrays = "0.0.10-0.1"

["0.6-0.7"]
julia = "0.5-0.6"

["0.6-0.8"]
WinReg = "0.2"

["0.7"]
Compat = "0.17-0.37"
DataFrames = "0.9-0.10"

["0.7-0.8"]
AxisArrays = "0.0.6-0.2"
DataStructures = "0.5-0.7"
NamedArrays = "0.5.3-0.6"
NullableArrays = "0.1"

["0.7.0-0.7.4"]
CategoricalArrays = "0.1"

["0.7.5-0.8"]
CategoricalArrays = "0.1-0.2"

["0.8"]
julia = "0.6"
Compat = "0.34-0.37"
DataArrays = "0.5-0.6"
DataFrames = "0.10"
Nulls = "0.1"
