["0.0"]
IterableTables = "0.2-0.4"

["0.0-0.1"]
DataFrames = "0.10"
DataValues = "0.1-0.3"
ReadStat = "0.1.1"

["0.0-0.2"]
julia = "0.6"
FileIO = "0.4-0.6"

["0.1"]
TableTraits = "0.0-0.1"

["0.1-0.2"]
IterableTables = "0.5-0.6"

["0.2"]
DataValues = "0.3"
IteratorInterfaceExtensions = "0.0.2"
ReadStat = "0.2"
TableTraits = "0.0.3-0.1"
TableTraitsUtils = "0.1.2-0.1.3"
