["0.0"]
Logging = "0.0-0.3"

["0.0-0.3"]
ArgParse = "0.2-0.5"

["0.0.1"]
julia = "0.3-0.6"

["0.0.2-0.2"]
julia = "0.4-0.6"

["0.0.2-0.3"]
YAML = "0.1-0.2"

["0.1"]
BuildExecutable = "0.0-0.1"

["0.2"]
Compat = "0.0-0.44"

["0.2-0.3"]
Mocking = "0.0-0.4"

["0.3"]
julia = "0.5-0.6"
FilePaths = "0.2-0.4"
Memento = "0.0-0.5"

["0.3-0.4"]
Compat = "0.17-0.44"

["0.4"]
julia = "0.6"
ArgParse = "0.5"
FilePaths = "0.3-0.4"
Memento = "0.2-0.5"
Mocking = "0.3.4-0.4"
YAML = "0.2.1"
