["0.1-0.7.0"]
Optim = "0.1-0.4"

["0.1-0.11"]
Calculus = "0.1-0.2"

["0.1.0-0.1.2"]
julia = "0.2-0.4"

["0.1.2-0.5"]
DualNumbers = "0.0-0.3"

["0.1.3-0.5"]
julia = "0.3-0.4"

["0.3.1-0.5"]
Compat = "0.0-0.31"

["0.4-0.11"]
Distances = "0.1-0.5"

["0.6"]
ForwardDiff = "0.0-0.5"

["0.6-0.8"]
LineSearches = "0.0-0.1"

["0.6-0.9"]
julia = "0.4-0.6"

["0.7.0-0.7.1"]
ForwardDiff = "0.1.4-0.1.8"

["0.7.1"]
Compat = "0.7.16-0.31"

["0.7.1-0.10.0"]
Optim = "0.1-0.9"

["0.7.2-0.7.3"]
Compat = "0.8-0.31"

["0.7.2-0.8"]
ForwardDiff = "0.2-0.5"

["0.8-0.9"]
Compat = "0.8.4-0.31"

["0.9"]
ForwardDiff = "0.3-0.5"
LineSearches = "0.1.2-0.1.5"

["0.9-0.11"]
DiffBase = "0.0-0.3"

["0.10-0.11"]
julia = "0.6"
ForwardDiff = "0.5"
LineSearches = "0.0-2.2"

["0.10.1-0.11"]
NLSolversBase = "2.1"
