["0.1"]
julia = "0.4-0.6"
MathProgBase = "0.5"

["0.1-0.4"]
BinDeps = "0.0-0.6"

["0.1.2-0.4"]
Compat = "0.8.6-0.33"

["0.2-0.3"]
julia = "0.5-0.6"

["0.2-0.4"]
MathProgBase = "0.5-0.6"

["0.4"]
julia = "0.6"
