["0.0"]
julia = "0.6"
ArgParse = "0.2-0.5"
BioSequences = "0.5-0.8"
Distributions = "0.1-0.15"
Glob = "1.0-1.1"
IterTools = "0.1-0.2"
Parameters = "0.0-0.8"
StatsBase = "0.1-0.19"
TestSetExtensions = "0.0-1.1"
