["0.0-0.2"]
julia = "0.5-0.6"
DataStructures = "0.4.6-0.7"

["0.0-0.3"]
LightXML = "0.4-0.5"

["0.0.1"]
StaticArrays = "0.0.4-0.6"

["0.0.1-0.0.2"]
ODE = "0.2.1-0.7"

["0.0.1-0.0.3"]
Quaternions = "0.1-0.3"

["0.0.2"]
StaticArrays = "0.0.11-0.6"

["0.0.3-0.0.4"]
StaticArrays = "0.1-0.6"

["0.0.4"]
Rotations = "0.3.3-0.6"

["0.0.5-0.2"]
DocStringExtensions = "0.3.1-0.4"
Rotations = "0.3.4-0.6"
StaticArrays = "0.2.1-0.6"

["0.1"]
Compat = "0.18-0.31"

["0.2"]
Compat = "0.19-0.31"

["0.3"]
julia = "0.6"
Compat = "0.27-0.31"
DocStringExtensions = "0.4"
Rotations = "0.6"
StaticArrays = "0.6.2"
TypeSortedCollections = "0.1"
