["0.1-1.2"]
julia = "0.4-0.6"
ArgParse = "0.2-0.5"
AutoHashEquals = "0.0-0.1"
DataStructures = "0.2-0.6"
Formatting = "0.1-0.3"
GZip = "0.1-0.3"
IndexedArrays = "0.0-0.3"
LightXML = "0.1-0.5"
PairwiseListMatrices = "0.0-0.5"

["1.0-1.2"]
Clustering = "0.2-0.9"

["1.0-1.2.2"]
ROCAnalysis = "0.0-0.1"

["1.1"]
FastaIO = "0.1-0.3"
FixedSizeArrays = "0.0-0.2"
PlotRecipes = "0.0-0.2"

["1.2"]
FixedSizeArrays = "0.2.3-0.2.5"
RecipesBase = "0.0-0.2"

["1.2.0"]
FastaIO = "0.2-0.3"

["1.2.1-1.2.3"]
FastaIO = "0.1-0.3"

["1.2.3"]
ROCAnalysis = "0.1"
