["0.0-0.1"]
julia = "0.6-0.7"

["0.0.6-0.3"]
DataStructures = "0.2-0.7"

["0.1.1-0.3"]
FileWatching = "0.7"

["0.2-0.3"]
julia = "0.7"
Dates = "0.7"
Test = "0.7"

["0.2.1"]
Compat = "0.50-0.53"

["0.2.1-0.3"]
Unicode = "0.7"

["0.3"]
Compat = "0.51-0.53"
