["0.1-0.2"]
julia = "0.4-0.6"
Compat = "0.9-0.44"

["0.1-0.4"]
QuantEcon = "0.0-0.14"

["0.3-0.4"]
julia = "0.5-0.6"
Combinatorics = "0.0-0.5"
Compat = "0.17-0.44"

["0.3-0.4.0"]
Iterators = "0.1-0.3"

["0.4.1"]
IterTools = "0.1-0.2"
