["0.1-0.2.0"]
julia = "0.1-0.6"

["0.2.1-0.2.3"]
julia = "0.2-0.6"

["0.2.4-0.3"]
ArrayViews = "0.3-0.6"
StatsBase = "0.3-0.18"

["0.2.4-0.5"]
julia = "0.3-0.6"

["0.4-0.5.0"]
ArrayViews = "0.4-0.6"

["0.4-0.7"]
Reexport = "0.0"

["0.4.0"]
StatsBase = "0.6.2-0.18"

["0.4.1-0.5.0"]
StatsBase = "0.6.3-0.18"

["0.5-0.6"]
Iterators = "0.1-0.3"

["0.5.1-0.5.3"]
ArrayViews = "0.4.8-0.6"

["0.5.1-0.7"]
StatsBase = "0.6.9-0.18"

["0.5.2-0.5.3"]
Compat = "0.0-0.31"

["0.6"]
julia = "0.4-0.6"
Compat = "0.8.7-0.31"

["0.7"]
julia = "0.6"
IterTools = "0.1"
