["0.0"]
julia = "0.5-0.6"

["0.0-0.1"]
Requests = "0.0-0.5"
URIParser = "0.0-0.2"

["0.0.1-0.0.3"]
JSON = "0.1-0.14"

["0.0.2-0.0.3"]
MbedTLS = "0.1-0.5"

["0.0.4"]
Compat = "0.17-0.31"

["0.0.4-0.1"]
JSON = "0.7-0.14"
Libz = "0.0-0.2"
MbedTLS = "0.4-0.5"
MsgPack = "0.0-0.1"

["0.1"]
julia = "0.6"
