["0.1"]
julia = "0.5-0.7"
POMDPs = "0.1-0.6"

["0.1-0.2"]
Distributions = "0.1-0.15"
Iterators = "0.1-0.3"
ProgressMeter = "0.0-0.5"

["0.1.0"]
StatsBase = "0.1-0.20"

["0.1.2-0.2"]
StatsBase = "0.15-0.20"

["0.2"]
julia = "0.6-0.7"
POMDPs = "0.6"

["0.2.5-0.2.6"]
DataFrames = "0.11"
