["0.1"]
julia = "0.5-0.6"
POMDPs = "0.1-0.6"

["0.1-0.2"]
Distributions = "0.1-0.14"
Iterators = "0.1-0.3"
ProgressMeter = "0.0-0.4"

["0.1.0"]
StatsBase = "0.1-0.19"

["0.1.2-0.2"]
StatsBase = "0.15-0.19"

["0.2"]
julia = "0.6"
POMDPs = "0.6"
