["0.1"]
julia = "0.5"
Clustering = "0.7"
Distances = "0.4"
FileIO = "0.3"
Gadfly = "0.5"
JLD = "0.6"
Measures = "0.0"
StatsBase = "0.13"

["0.2"]
julia = "0.6"
Clustering = "0.9"
Distances = "0.5"
FileIO = "0.5-0.6"
Gadfly = "0.6"
JLD = "0.8"
Measures = "0.1"
StatsBase = "0.18-0.19"
