["0.0"]
julia = "0.4-0.6"
Polyhedra = "0.0"

["0.0-0.1"]
MathProgBase = "0.1-0.6"

["0.0-0.2"]
BinDeps = "0.0-0.6"

["0.1"]
julia = "0.5-0.6"

["0.1-0.2"]
WinRPM = "0.1-0.2"

["0.1.0"]
Polyhedra = "0.1.0-0.1.1"

["0.1.1"]
Polyhedra = "0.1.2"

["0.1.1-0.2"]
Homebrew = "0.0-0.5"

["0.1.2"]
Polyhedra = "0.1.3"

["0.1.3"]
Polyhedra = "0.1.4-0.1.5"

["0.1.4"]
Polyhedra = "0.1.5"

["0.2"]
julia = "0.6"
MathProgBase = "0.6"
Polyhedra = "0.2"
