["0.1-0.3"]
Options = "0.1-0.2"

["0.1-0.3.0"]
Distributions = "0.1-0.15"

["0.1-0.4.2"]
julia = "0.2-0.4"

["0.1-0.11"]
Calculus = "0.1-0.2"

["0.2-0.4.4"]
DualNumbers = "0.0-0.3"

["0.4.1-0.4.4"]
Compat = "0.0-0.39"

["0.4.3-0.4.4"]
julia = "0.3-0.4"

["0.4.5"]
DualNumbers = "0.2-0.3"
PositiveFactorizations = "0.0-0.1"

["0.4.5-0.6"]
LineSearches = "0.0-0.1"

["0.4.5-0.7"]
julia = "0.4-0.6"
NLSolversBase = "0.0-2.1"

["0.4.6"]
Compat = "0.0-0.39"
DualNumbers = "0.0-0.3"

["0.4.7-0.5"]
DualNumbers = "0.2-0.3"

["0.4.7-0.11"]
PositiveFactorizations = "0.0-0.1"

["0.5"]
Compat = "0.7.16-0.39"

["0.6"]
ForwardDiff = "0.2"

["0.6-0.7.5"]
Compat = "0.8.4-0.39"

["0.7.0-0.7.2"]
LineSearches = "0.1"

["0.7.0-0.7.7"]
ForwardDiff = "0.3"

["0.7.3-0.7.8"]
LineSearches = "0.1.2-0.1.5"

["0.7.7-0.11"]
Compat = "0.18-0.39"

["0.7.8"]
ForwardDiff = "0.3-0.4"

["0.9"]
NLSolversBase = "2.1"

["0.9-0.10"]
LineSearches = "2.1-3.2"

["0.9-0.11"]
julia = "0.6"
ForwardDiff = "0.5-0.7"

["0.10-0.11"]
NLSolversBase = "3.0-3.1"

["0.11"]
LineSearches = "3.2"
