["0.0"]
julia = "0.5-0.6"
ChainRecursive = "0.0-0.1"
CreateMacrosFrom = "0.0"
DataStructures = "0.2-0.6"
MacroTools = "0.1-0.3"

["0.1"]
julia = "0.6"
DataStructures = "0.5.2-0.6"

["0.1.0"]
MacroTools = "0.3.3-0.3.7"

["0.1.1"]
MacroTools = "0.3.1-0.3.7"
