["0.0"]
julia = "0.5-0.6"
ChainRecursive = "0.0-0.1"
CreateMacrosFrom = "0.0"
DataStructures = "0.2-0.7"
MacroTools = "0.1-0.4"

["0.1-0.2"]
julia = "0.6"
DataStructures = "0.5.2-0.7"

["0.1.0"]
MacroTools = "0.3.3-0.4"

["0.1.1-0.2"]
MacroTools = "0.3.1-0.4"
