["0.0"]
DataFrames = "0.1-0.10"
JSON = "0.1-0.15"
Mustache = "0.0-0.3"

["0.0.1-0.0.2"]
julia = "0.2-0.6"

["0.0.1-0.0.3"]
Datetime = "0.1"

["0.0.2-0.0.7"]
DataArrays = "0.0-0.6"

["0.0.3"]
julia = "0.3-0.6"

["0.0.4"]
julia = "0.4-0.6"

["0.0.5-0.0.7"]
julia = "0.3-0.6"
Dates = "0.0-0.4"
