["0.0"]
Sundials = "0.3-0.14"

["0.0-0.1.0"]
DiffEqBase = "0.0-0.6"

["0.0-0.6"]
NLsolve = "0.7.3-0.11"
Ranges = "0.0"
RecipesBase = "0.1-0.2"

["0.0-1.4"]
Compat = "0.8.8-0.31"

["0.0-2.3.1"]
InplaceOps = "0.0.5-0.1"

["0.0-2.4"]
julia = "0.5-0.6"
ForwardDiff = "0.2.4-0.5"

["0.0-2.19"]
GenericSVD = "0.0.2-0.1"
Parameters = "0.5-0.7"

["0.0.2-0.0.3"]
ParameterizedFunctions = "0.1-2.2"

["0.0.4-0.1.0"]
RecursiveArrayTools = "0.0-0.12"

["0.1.0"]
Juno = "0.1-0.3"

["0.1.1"]
DiffEqBase = "0.1.2-0.6"

["0.1.1-0.6"]
RecursiveArrayTools = "0.0.2-0.12"

["0.1.1-2.19"]
Juno = "0.2.5-0.3"

["0.2-0.5"]
DiffEqBase = "0.2-0.6"

["0.2-2.16"]
Calculus = "0.1.15-0.2"

["0.6"]
DiffEqBase = "0.4-0.6"

["1.0"]
DiffEqBase = "0.6-0.7"

["1.0-1.1"]
RecursiveArrayTools = "0.1.2-0.12"

["1.0-2.19"]
DataStructures = "0.4.6-0.7"
NLsolve = "0.9.1-0.11"
Roots = "0.2.1-0.4"

["1.1"]
DiffEqBase = "0.7"

["1.1-2.4"]
Iterators = "0.1-0.3"

["1.2-1.3"]
DiffEqBase = "0.8-0.14"

["1.2-2.0.2"]
RecursiveArrayTools = "0.2-0.12"

["1.4-1.5"]
DiffEqBase = "0.11-0.14"

["1.5-2.0.1"]
Compat = "0.17-0.31"

["1.6-1.7"]
DiffEqBase = "0.13-0.14"

["1.8"]
DiffEqBase = "0.15-1.14"

["2.0.0-2.0.2"]
DiffEqBase = "1.1-1.14"

["2.0.2-2.19"]
Compat = "0.18-0.31"

["2.0.3-2.1"]
DiffEqBase = "1.3-1.14"

["2.0.3-2.2.0"]
RecursiveArrayTools = "0.6-0.12"

["2.2-2.5"]
DiffEqBase = "1.5-1.14"

["2.2.1-2.4"]
RecursiveArrayTools = "0.7.1-0.12"

["2.3-2.5"]
StaticArrays = "0.0-0.6"

["2.5-2.16"]
RecursiveArrayTools = "0.8-0.12"

["2.5-2.19"]
julia = "0.6"
ForwardDiff = "0.5"

["2.6-2.7"]
DiffEqBase = "1.10-1.14"

["2.7-2.19"]
Reexport = "0.0"

["2.8-2.9"]
DiffEqBase = "1.11-1.14"

["2.10-2.11"]
DiffEqBase = "1.15"

["2.12-2.13"]
DiffEqBase = "1.16-1.18"
MuladdMacro = "0.0"

["2.14-2.18"]
DiffEqBase = "1.20-1.23"

["2.14-2.19"]
MuladdMacro = "0.0.2"
StaticArrays = "0.0-0.6"

["2.17-2.19"]
DiffEqDiffTools = "0.0"
RecursiveArrayTools = "0.12"

["2.19"]
DiffEqBase = "1.23"
