["0.0"]
Docile = "0.0-0.5"

["0.0-0.2"]
DataFrames = "0.1-0.10"
DataStructures = "0.2-0.7"
Distributions = "0.1-0.14"

["0.0.1-0.0.2"]
julia = "0.3-0.6"
Compat = "0.0-0.31"

["0.0.3-0.2"]
julia = "0.4-0.6"

["0.1-0.2"]
Documenter = "0.1-0.11"

["0.2"]
Compat = "0.8.6-0.31"

["0.3"]
julia = "0.5-0.6"
DataFrames = "0.8.4-0.10"
DataStructures = "0.4.6-0.7"
Distributions = "0.11-0.14"
Documenter = "0.9-0.11"
JSON = "0.1-0.14"
NamedArrays = "0.5.3-0.6"
Plots = "0.9.4-0.12"
