["0.4-0.6"]
StaticArrays = "0.6.1-0.6.6"

["0.4-0.7"]
julia = "0.6"
Compat = "0.28-0.44"
Distributions = "0.11.1-0.15"
Polynomials = "0.0-0.2"

["0.7"]
RecipesBase = "0.0-0.2"
StaticArrays = "0.6.3-0.6.6"
