["0.1"]
julia = "0.5-0.7"
LeastSquaresOptim = "0.2-0.5"

["0.1-0.2"]
Distances = "0.1.1-0.5"
Reexport = "0.0-0.1"
StatsBase = "0.7.1-0.20"

["0.1-0.2.1"]
DataArrays = "0.0-0.6"
DataFrames = "0.6-0.10"

["0.1.0"]
FixedEffectModels = "0.3-0.5"

["0.1.1"]
FixedEffectModels = "0.3.1-0.5"

["0.2"]
julia = "0.6-0.7"
Iterators = "0.1-0.3"

["0.2.0"]
LeastSquaresOptim = "0.3-0.5"

["0.2.0-0.2.1"]
FixedEffectModels = "0.4-0.5"

["0.2.1"]
LeastSquaresOptim = "0.4-0.5"

["0.2.2"]
DataFrames = "0.11"
FixedEffectModels = "0.5"
LeastSquaresOptim = "0.5"
StatsModels = "0.0-0.2"
