["0.1"]
julia = "0.5-0.6"
LeastSquaresOptim = "0.2-0.4"

["0.1-0.2"]
DataArrays = "0.0-0.6"
DataFrames = "0.6-0.10"
Distances = "0.1.1-0.5"
Reexport = "0.0"
StatsBase = "0.7.1-0.19"

["0.1.0"]
FixedEffectModels = "0.3-0.4"

["0.1.1"]
FixedEffectModels = "0.3.1-0.4"

["0.2"]
julia = "0.6"
FixedEffectModels = "0.4"
Iterators = "0.1-0.3"

["0.2.0"]
LeastSquaresOptim = "0.3-0.4"

["0.2.1"]
LeastSquaresOptim = "0.4"
