["0.0"]
julia = "0.3-0.6"
FactCheck = "0.0-0.4"
GZip = "0.1-0.3"
MathProgBase = "0.1-0.6"

["0.0-0.1"]
Codecs = "0.1-0.3"
LightXML = "0.1-0.5"
Requests = "0.0-0.5"

["0.1"]
julia = "0.4-0.6"
Libz = "0.0-0.2"
MathProgBase = "0.4-0.5"
