["0.1-0.2.0"]
julia = "0.2-0.6"

["0.2"]
Homebrew = "0.0-0.5"

["0.2-0.4.0"]
BinDeps = "0.0-0.6"

["0.2.1"]
julia = "0.3-0.6"

["0.3"]
julia = "0.4-0.6"

["0.3-0.4.0"]
Compat = "0.0-0.31"
Conda = "0.1-0.7"

["0.3-0.5"]
Formatting = "0.1-0.3"

["0.4-0.5"]
julia = "0.5-0.6"

["0.4.1-0.5"]
BinDeps = "0.4-0.6"
Conda = "0.3-0.7"

["0.5"]
Compat = "0.19-0.31"
