["0.0"]
Catalan = "0.0"

["0.0-0.1"]
julia = "0.3-0.6"

["0.0-0.2.0"]
Distributions = "0.1-0.14"
ODE = "0.1-0.7"

["0.1"]
Combinatorics = "0.0-0.4"

["0.2"]
julia = "0.4-0.6"
Combinatorics = "0.2-0.4"

["0.2.0"]
Docile = "0.0-0.5"

["0.2.1"]
Compat = "0.9.2-0.31"
Distributions = "0.8.10-0.14"
GSL = "0.3.1-0.3.6"
ODE = "0.2.1-0.7"
