["0.1-0.2.1"]
julia = "0.4-0.6"

["0.1-0.3"]
BlackBoxOptim = "0.0-0.3"
DataFrames = "0.1-0.10"
Distributions = "0.1-0.15"
ForwardDiff = "0.0-0.7"

["0.1.0-0.1.5"]
Lora = "0.4.4-0.5"

["0.1.0-0.1.8"]
Mads = "0.1-0.4"

["0.1.6"]
Lora = "0.3-0.5"

["0.1.6-0.3"]
RobustPmap = "0.1-0.2"

["0.1.7-0.3"]
Klara = "0.6-0.9"

["0.1.9-0.3"]
AffineInvariantMCMC = "0.1-0.2"

["0.2.2-0.3"]
julia = "0.5-0.6"
