["0.0-0.1"]
julia = "0.3-0.6"
Graphs = "0.2-0.8"
TikzPictures = "0.0-1.2"

["0.0.2-0.1"]
LightGraphs = "0.1-0.11"

["0.1"]
Compat = "0.0-0.33"

["0.2-0.4"]
Compat = "0.8-0.33"

["0.2-0.5"]
julia = "0.4-0.6"
LightGraphs = "0.6-0.11"
TikzPictures = "0.3.5-1.2"

["0.5"]
Compat = "0.17-0.33"
