["0.0"]
julia = "0.4.1-0.4.7"
DataStreams = "0.0.6"
SQLite = "0.3.3-0.5"

["0.0-0.2"]
ArgParse = "0.3-0.5"
BaseTestNext = "0.2.1-0.2.2"
Gumbo = "0.2-0.4"
HttpCommon = "0.2.6-0.3"
LightXML = "0.2.1-0.5"
Requests = "0.3.8-0.5"
XMLconvert = "0.0-0.1"
ZipFile = "0.2.6-0.4"

["0.1"]
julia = "0.4.1-0.6"

["0.1-0.2"]
DataStreams = "0.0.10-0.1"
MySQL = "0.0.2-0.2"
SQLite = "0.3.5-0.5"

["0.1.1-0.2"]
DataFrames = "0.8.3-0.10"
NullableArrays = "0.0.8-0.1"

["0.2"]
julia = "0.5-0.6"
DataStructures = "0.4.6-0.7"
