["0.0"]
julia = "0.4-0.6"

["0.0-0.1"]
Dates = "0.0-0.4"

["0.0.6-0.4"]
Requests = "0.0-0.5"

["0.1-0.3"]
julia = "0.5-0.6"

["0.2.5-0.4"]
JSON = "0.1-0.16"

["0.4"]
julia = "0.6"

["0.4.1-0.4.6"]
RecipesBase = "0.0-0.2"
