["0.0"]
julia = "0.3"
ApproxFun = "0.0.7"

["0.1"]
julia = "0.4"

["0.1.0"]
ApproxFun = "0.1"

["0.1.1"]
ApproxFun = "0.2"

["0.1.1-0.2.0"]
Compat = "0.8.4-0.33"

["0.1.1-0.2.1"]
Plots = "0.0-0.13"

["0.1.2"]
ApproxFun = "0.2.1-0.2.2"

["0.1.3"]
ApproxFun = "0.3.0"

["0.1.4"]
ApproxFun = "0.3.1-0.3.3"

["0.1.5"]
ApproxFun = "0.3.2-0.3.3"

["0.2-0.3"]
DualNumbers = "0.2.3-0.3"

["0.2.0"]
ApproxFun = "0.4.0"

["0.2.0-0.2.1"]
julia = "0.5"

["0.2.0-0.2.2"]
BandedMatrices = "0.1.2-0.3"

["0.2.1"]
ApproxFun = "0.4.1"

["0.2.1-0.2.2"]
Compat = "0.9.5-0.33"

["0.2.2"]
ApproxFun = "0.5"

["0.2.2-0.2.3"]
julia = "0.5-0.6"

["0.2.2-0.3"]
RecipesBase = "0.1-0.2"

["0.2.3"]
ApproxFun = "0.6"
BandedMatrices = "0.2.2-0.3"

["0.2.3-0.3"]
Compat = "0.18-0.33"

["0.3"]
julia = "0.6"
ApproxFun = "0.7"
BandedMatrices = "0.3"
