["0.0-0.2"]
julia = "0.4-0.6"

["0.2-0.3.0"]
DataFrames = "0.6.10-0.10"

["0.2.6"]
Compat = "0.0-0.31"

["0.2.6-0.3.0"]
Reexport = "0.0"

["0.2.7-0.2.9"]
Compat = "0.7.20-0.31"

["0.3"]
julia = "0.5-0.6"

["0.3.1"]
AxisArrays = "0.0-0.2"
StatsBase = "0.1-0.19"

["0.3.1-0.3.2"]
DataTables = "0.0"

["0.3.2"]
AxisArrays = "0.1-0.2"
Compat = "0.18-0.31"
StatsBase = "0.6-0.19"
