["0.0"]
julia = "0.5-0.6"
LazyContext = "0.0"
MacroTools = "0.1-0.3"

["0.0-0.1"]
DataFrames = "0.1-0.10"

["0.0-0.1.1"]
Query = "0.0-0.6"

["0.1"]
julia = "0.6"
ChainRecursive = "0.0.3-0.1"
NamedTuples = "0.0-4.0"

["0.1.0"]
LazyContext = "0.1.1-0.1.2"
MacroTools = "0.3.3-0.3.7"

["0.1.1-0.1.2"]
DataArrays = "0.0-0.6"
LazyCall = "0.1.1"
LazyContext = "0.1.2"
MacroTools = "0.3.2-0.3.7"

["0.1.2"]
Query = "0.0-0.7"
