["0.0-0.2"]
DiffEqBase = "0.0-2.6"

["0.0-0.4"]
julia = "0.5-0.6"

["0.1-0.6"]
RecursiveArrayTools = "0.0-0.13"

["0.3-0.6"]
DiffEqBase = "0.13-2.6"

["0.3.1-0.6"]
Compat = "0.19-0.39"

["0.4-0.6"]
Juno = "0.1-0.3"

["0.5-0.6"]
julia = "0.6"
