["0.0-0.2"]
DiffEqBase = "0.0-1.22"

["0.0-0.4"]
julia = "0.5-0.6"

["0.1-0.5"]
RecursiveArrayTools = "0.0-0.12"

["0.3-0.5"]
DiffEqBase = "0.13-1.22"

["0.3.1-0.5"]
Compat = "0.19-0.31"

["0.4-0.5"]
Juno = "0.1-0.3"

["0.5"]
julia = "0.6"
