["0.1"]
Dagger = "0.2-0.3"

["0.1-0.2"]
NullableArrays = "0.0-0.1"

["0.1-0.2.2"]
TextParse = "0.1.6-0.2"

["0.1-0.4"]
julia = "0.6"
Glob = "1.1.1"
NamedTuples = "4.0"
PooledArrays = "0.0.2-0.1"

["0.1.0-0.1.2"]
IndexedTables = "0.1.4-0.2"

["0.1.3-0.1.5"]
IndexedTables = "0.2.1"

["0.2-0.3.5"]
IndexedTables = "0.3-0.4"

["0.2.0"]
Dagger = "0.2.1-0.3"

["0.2.1-0.2.3"]
Dagger = "0.3"

["0.2.3"]
TextParse = "0.2"

["0.3-0.4"]
Dagger = "0.4-0.5"
DataValues = "0.0-0.3"
MemPool = "0.0"
TextParse = "0.3"

["0.3.6"]
OnlineStatsBase = "0.0.8-0.2"

["0.3.6-0.3.7"]
IndexedTables = "0.3.3-0.4"

["0.3.6-0.4"]
StatsBase = "0.1-0.19"

["0.3.7-0.4"]
OnlineStats = "0.13"

["0.4.0"]
IndexedTables = "0.4"

["0.4.1"]
IndexedTables = "0.4.1-0.4.2"

["0.4.2"]
IndexedTables = "0.4.2"
