["0.1"]
Dagger = "0.2-0.3"

["0.1-0.2"]
NullableArrays = "0.0-0.1"

["0.1-0.2.2"]
TextParse = "0.1.6-0.2"

["0.1-0.3"]
julia = "0.6"
Glob = "1.1.1"
NamedTuples = "4.0"
PooledArrays = "0.0.2-0.1"

["0.1.0-0.1.2"]
IndexedTables = "0.1.4-0.2"

["0.1.3-0.1.5"]
IndexedTables = "0.2.1"

["0.2-0.3"]
IndexedTables = "0.3"

["0.2.0"]
Dagger = "0.2.1-0.3"

["0.2.1-0.2.3"]
Dagger = "0.3"

["0.2.3"]
TextParse = "0.2"

["0.3"]
Dagger = "0.4"
DataValues = "0.0-0.3"
MemPool = "0.0"
TextParse = "0.3"
