["0.0"]
julia = "0.4-0.6"

["0.0.1"]
Compat = "0.0-0.31"
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"
FileIO = "0.0-0.5"
GZip = "0.1-0.3"

["0.0.2-0.0.3"]
FileIO = "0.1-0.5"

["0.0.2-0.0.4"]
Compat = "0.8-0.31"

["0.0.2-0.1"]
DataArrays = "0.3-0.6"
DataFrames = "0.7-0.10"
GZip = "0.2-0.3"

["0.0.4-0.1"]
FileIO = "0.1.2-0.5"

["0.1"]
julia = "0.5-0.6"
Compat = "0.17-0.31"
