["0.1"]
julia = "0.4-0.6"
FixedSizeArrays = "0.0-0.2"
Rotations = "0.0-0.6"

["0.2"]
julia = "0.4-0.5"
Compat = "0.8-0.10"
FixedSizeArrays = "0.2.2-0.2.5"
Rotations = "0.1-0.2"

["0.3-0.4"]
julia = "0.5-0.6"
Rotations = "0.3-0.6"
StaticArrays = "0.0-0.6"

["0.4.1"]
Compat = "0.17-0.31"
