["0.0.1"]
julia = "0.2-0.6"

["0.0.2"]
julia = "0.1-0.6"

["0.0.5"]
julia = "0.3-0.6"
Compat = "0.0-0.44"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8.8-0.44"

["0.2"]
julia = "0.5-0.6"
Compat = "0.17-0.44"
