["0.0"]
FixedPointNumbers = "0.0-0.2"

["0.0-0.2"]
julia = "0.5-0.6"

["0.0-0.3"]
Colors = "0.4-0.8"
ColorVectorSpace = "0.1.11-0.4"
ImageAxes = "0.0-0.3"
ImageCore = "0.0-0.4"
IndirectArrays = "0.0-0.1"

["0.1-0.3"]
FixedPointNumbers = "0.3-0.4"

["0.2.1-0.3"]
Compat = "0.19-0.31"

["0.3"]
julia = "0.6"
