["0.0"]
julia = "0.3-0.6"
AWS = "0.1-0.3"
BDF = "0.0-0.3"
DataFrames = "0.1-0.10"
Distances = "0.1-0.5"
Distributions = "0.1-0.14"
Docile = "0.0-0.5"
DSP = "0.0-0.3"
Gadfly = "0.1-0.6"
Logging = "0.0-0.3"
MAT = "0.1-0.4"
NumericExtensions = "0.2-0.6"
ProgressMeter = "0.0-0.5"
SIUnits = "0.0-0.1"
Synchrony = "0.0"
Winston = "0.3-0.13"
