["0.0"]
StatsBase = "0.1-0.18"

["0.0.1"]
julia = "0.1-0.6"
DataFrames = "0.1-0.10"
Winston = "0.3-0.13"

["0.0.1-0.0.2"]
Datetime = "0.1"
TimeSeries = "0.0-0.10"

["0.0.2"]
julia = "0.3-0.6"

["0.0.2-0.0.3"]
Distributions = "0.1-0.14"
NLopt = "0.0-0.3"
Optim = "0.1-0.4"

["0.0.3"]
julia = "0.3-0.4"
Compat = "0.0-0.31"
Dates = "0.0-0.4"
TimeSeries = "0.5.11-0.10"
