["0.0-0.1"]
StatsBase = "0.1-0.19"

["0.0.1"]
julia = "0.1-0.6"
DataFrames = "0.1-0.10"
Winston = "0.3-0.13"

["0.0.1-0.0.2"]
Datetime = "0.1"
TimeSeries = "0.0-0.11"

["0.0.2"]
julia = "0.3-0.6"

["0.0.2-0.0.3"]
Optim = "0.1-0.4"

["0.0.2-0.1"]
Distributions = "0.1-0.15"
NLopt = "0.0-0.3"

["0.0.3"]
julia = "0.3-0.4"
Dates = "0.0-0.4"

["0.0.3-0.1"]
Compat = "0.0-0.44"
TimeSeries = "0.5.11-0.11"

["0.1"]
julia = "0.6"
Optim = "0.1-0.11"
