["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.3"]
NetCDF = "0.4.1-0.6"

["0.0.2-0.0.3"]
PyCall = "1.7.2-1.15"
PyPlot = "2.2.4-2.3"

["0.0.4-0.1"]
Shapefile = "0.0.3-0.3"

["0.0.5-0.1"]
AxisArrays = "0.0.6-0.2"
PyCall = "1.10-1.15"

["0.0.5-0.2"]
PyPlot = "2.3.1-2.3.2"

["0.0.5-0.3"]
ArgCheck = "0.1-0.4"

["0.1"]
Lint = "0.3-0.5"

["0.2-0.3"]
julia = "0.6"
AxisArrays = "0.1.3-0.2"
PyCall = "1.11.1-1.15"
Shapefile = "0.2-0.3"

["0.3"]
Interpolations = "0.7"
PyPlot = "2.3.2"
