["0.1.0-0.1.7"]
julia = "0.3-0.7"

["0.1.7-2.0"]
Compat = "0.0-0.53"

["0.1.8-1.0"]
julia = "0.4-0.7"

["1.1"]
julia = "0.5.2-0.7"

["1.1-2.0"]
SpecialFunctions = "0.0-0.3"

["2.0"]
julia = "0.7"
Test = "0.7"
