["0.0-0.1"]
julia = "0.4-0.6"

["0.0-0.2"]
Colors = "0.4-0.8"
Gadfly = "0.1-0.6"

["0.0.4-0.2"]
Cairo = "0.0-0.3"
Fontconfig = "0.0-0.1"

["0.1-0.2"]
Compose = "0.1-0.5"

["0.2"]
julia = "0.5-0.6"

["0.2.1-0.2.4"]
Distributions = "0.1-0.14"
