["0.0"]
DiffEqBase = "0.0-0.14"
ODEInterface = "0.0-0.1"

["0.0-0.5"]
julia = "0.5-0.6"

["0.1"]
DiffEqBase = "0.4.1-0.14"

["0.1-0.4"]
ODEInterface = "0.0.11-0.1"

["0.2-0.4.0"]
DiffEqBase = "0.15-1.22"

["0.3.1-0.5"]
Compat = "0.17-0.31"

["0.4.1-0.5"]
DiffEqBase = "1.5.1-1.22"

["0.5"]
ODEInterface = "0.1.3-0.1.5"
Reexport = "0.0"
