["0.0"]
DiffEqBase = "0.0-0.14"
ODEInterface = "0.0-0.1"

["0.0-0.5"]
julia = "0.5-0.6"

["0.1"]
DiffEqBase = "0.4.1-0.14"

["0.1-0.4"]
ODEInterface = "0.0.11-0.1"

["0.2-0.4.0"]
DiffEqBase = "0.15-2.10"

["0.3.1-0.6"]
Compat = "0.17-0.44"

["0.4.1-0.6"]
DiffEqBase = "1.5.1-2.10"

["0.5-0.6"]
ODEInterface = "0.1.3-0.1.5"
Reexport = "0.0-0.1"

["0.6"]
julia = "0.6"
DataStructures = "0.2-0.7"
FunctionWrappers = "0.0-0.1"
Roots = "0.1-0.4"
