["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.2"]
ColorTypes = "0.4-0.6"
Compat = "0.17-0.31"
CoordinateTransformations = "0.4"
FileIO = "0.0-0.5"
IdentityRanges = "0.0"
ImageCore = "0.1.2-0.4"
ImageFiltering = "0.1.4-0.2"
ImageTransformations = "0.3-0.4"
Interpolations = "0.6"
OffsetArrays = "0.1-0.3"
Rotations = "0.0-0.6"
ShowItLikeYouBuildIt = "0.0-0.1"
StaticArrays = "0.0-0.6"

["0.2"]
julia = "0.6"
ComputationalResources = "0.0.2-0.1"
MappedArrays = "0.0.3-0.0.7"
MLDataPattern = "0.1.2"
