["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.3"]
Compat = "0.17-0.44"
CoordinateTransformations = "0.4"
FileIO = "0.0-0.6"
IdentityRanges = "0.0-0.1"
ImageFiltering = "0.1.4-0.2"
ImageTransformations = "0.3-0.4"
Interpolations = "0.6-0.7"
OffsetArrays = "0.1-0.4"
ShowItLikeYouBuildIt = "0.0-0.2"

["0.0-0.3.0"]
ColorTypes = "0.4-0.6"
ImageCore = "0.1.2-0.4"
Rotations = "0.0-0.6"
StaticArrays = "0.0-0.6.4"

["0.2-0.3"]
julia = "0.6"
ComputationalResources = "0.0.2-0.2"
MappedArrays = "0.0.3-0.0.7"
MLDataPattern = "0.1.2-0.3"

["0.3.1"]
ColorTypes = "0.6.6"
ImageCore = "0.5"
Rotations = "0.6.1"
StaticArrays = "0.6.5-0.6.6"
