["0.0.1"]
julia = "0.1-0.6"

["0.0.2"]
julia = "0.3-0.6"

["0.0.2-0.3.0"]
Compat = "0.0-0.44"
Lint = "0.0-0.5"

["0.0.2-1.1"]
DataArrays = "0.2.10-0.6"

["0.0.3-0.3"]
julia = "0.4-0.6"

["0.3.0"]
StatsBase = "0.1-0.19"

["0.3.1-1.1"]
Compat = "0.8-0.44"

["0.3.1-2.1"]
StatsBase = "0.8-0.19"

["1.0"]
DataStructures = "0.2-0.7"

["1.0-1.1"]
julia = "0.5-0.6"

["1.1-2.1"]
DataStructures = "0.5-0.7"

["2.0-2.1"]
julia = "0.6"
