["0.0-0.5"]
julia = "0.2-0.6"

["0.0-0.8"]
LightXML = "0.1-0.5"
Winston = "0.3-0.13"

["0.4-0.8"]
Graphs = "0.2-0.7"

["0.6-0.8"]
julia = "0.3-0.6"

["0.7-0.8"]
Compat = "0.0-0.31"

["0.8"]
Geodesy = "0.0-0.3"
LibExpat = "0.0-0.3"
Reexport = "0.0"
