["0.2-0.3"]
DataStructures = "0.2-0.7"

["0.2-0.3.1"]
julia = "0.2-0.6"

["0.3.2-0.6"]
julia = "0.3-0.6"

["0.4-0.5.3"]
DataStructures = "0.2.9-0.7"

["0.5.2"]
Compat = "0.0-0.37"

["0.5.3-0.6"]
Compat = "0.4-0.37"

["0.5.4-0.7"]
DataStructures = "0.3.8-0.7"

["0.7"]
julia = "0.4-0.6"
Compat = "0.7.16-0.37"

["0.8"]
julia = "0.5-0.6"
Compat = "0.18-0.37"
DataStructures = "0.5-0.7"
