["0.1-0.2"]
julia = "0.6"
Documenter = "0.1-0.12"
NetCDF = "0.1-0.6"
WriteVTK = "0.0-0.6"

["0.2"]
Compat = "0.9.1-0.37"
Homebrew = "0.0.4-0.6"
WinRPM = "0.1-0.3"

["0.2.0"]
BinDeps = "0.2.12-0.6"

["0.2.1"]
BinDeps = "0.3-0.6"
