["0.0-0.1.1"]
julia = "0.2-0.6"

["0.0-0.2"]
DataFrames = "0.1-0.10"

["0.0.3"]
DataArrays = "0.0-0.6"

["0.1.0"]
DataArrays = "0.1-0.6"

["0.1.1"]
DataArrays = "0.0-0.6"

["0.1.2"]
julia = "0.1-0.6"

["0.1.2-0.2"]
Reexport = "0.0"

["0.1.3"]
julia = "0.3-0.6"

["0.1.3-0.2"]
Compat = "0.0-0.31"

["0.2"]
julia = "0.4-0.6"
FileIO = "0.0-0.5"
RData = "0.0-0.1"
