["0.0"]
FixedPointNumbers = "0.0-0.2"

["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.2"]
CatIndices = "0.0-0.1"
Colors = "0.4-0.8"
ColorVectorSpace = "0.0-0.5"
ComputationalResources = "0.0-0.2"
DataStructures = "0.4.6-0.7"
FFTViews = "0.0-0.1"
ImageCore = "0.0-0.5"
MappedArrays = "0.0"
OffsetArrays = "0.1-0.4"
StaticArrays = "0.0.5-0.6"
TiledIteration = "0.0-0.1"

["0.1-0.2"]
FixedPointNumbers = "0.3-0.4"

["0.1.3-0.2"]
Compat = "0.18-0.37"

["0.2"]
julia = "0.6"
