["0.0"]
julia = "0.4-0.6"
Distances = "0.1-0.5"

["0.0.1-0.0.3"]
Devectorize = "0.2-0.4"

["0.0.4-0.1"]
Compat = "0.8.4-0.39"

["0.1"]
Distances = "0.3"

["0.1-0.2"]
julia = "0.5-0.6"

["0.1-0.3"]
StaticArrays = "0.0.4-0.6"

["0.2"]
Compat = "0.17-0.39"

["0.2-0.3"]
Distances = "0.4-0.5"

["0.3"]
julia = "0.6"
