["0.0.1-0.0.7"]
julia = "0.4-0.7"
Dates = "0.7"

["0.0.5"]
BinDeps = "0.0-0.8"

["0.0.6"]
Compat = "0.0-0.53"

["0.0.7-0.0.8"]
Compat = "0.7.15-0.53"

["0.0.8"]
julia = "0.4-0.5"

["0.1-0.3"]
julia = "0.6-0.7"
Dates = "0.7"

["0.2-0.3"]
DelimitedFiles = "0.7"
StaticArrays = "0.5-0.6"
Test = "0.7"
