["0.0"]
TestImages = "0.0-0.2"

["0.0-0.1"]
julia = "0.3-0.6"
FixedPointNumbers = "0.0-0.4"
Images = "0.2-0.11"
ImageView = "0.0-0.5"

["0.1"]
BinDeps = "0.0-0.6"
Color = "0.1-0.4"
MAT = "0.1-0.3"
Tk = "0.0-0.5"
