["0.0"]
julia = "0.5-0.6"
CreateMacrosFrom = "0.0"

["0.0.1"]
NumberedLines = "0.0-0.1"

["0.0.2-0.0.4"]
MacroTools = "0.1-0.3"

["0.0.3-0.1"]
NumberedLines = "0.0-0.1"

["0.0.4-0.1.0"]
Atom = "0.1-0.6"

["0.1"]
julia = "0.6"

["0.1.0"]
MacroTools = "0.3.3-0.3.7"

["0.1.1"]
MacroTools = "0.3.1-0.3.7"
