["0.1"]
julia = "0.5-0.6"
BioSequences = "0.6.2-0.6.3"
Compat = "0.17-0.31"

["0.1-0.2"]
Automa = "0.0-0.3"
BGZFStreams = "0.0-0.1"
BioCore = "1.1-1.2"
BufferedStreams = "0.0-0.3"
IntervalTrees = "0.0-0.3"
Twiddle = "0.1-0.4"

["0.2"]
julia = "0.6"
BioSequences = "0.7-0.8"
Combinatorics = "0.0-0.4"
