["0.0"]
Calendar = "0.1-0.4"
StatsBase = "0.1-0.19"
UTF16 = "0.2-0.3"

["0.0-0.2"]
julia = "0.1-0.6"
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"

["0.1-0.3"]
Datetime = "0.1"

["0.3-0.5.10"]
julia = "0.3-0.6"

["0.4-0.5"]
Dates = "0.0-0.4"

["0.5.9-0.5.10"]
Compat = "0.0-0.39"

["0.5.11"]
julia = "0.3"

["0.6-0.8.6"]
julia = "0.4"

["0.8.7-0.8.8"]
julia = "0.4-0.6"

["0.9-0.10"]
julia = "0.5-0.6"

["0.10"]
RecipesBase = "0.0-0.2"

["0.11"]
julia = "0.6"
RecipesBase = "0.2.3"
