["0.1"]
Graphs = "0.2-0.7"

["0.1-0.2"]
julia = "0.3-0.6"
JSON = "0.1-0.14"
Requests = "0.0-0.5"

["0.2"]
Compat = "0.0-0.31"

["0.2.0"]
LightGraphs = "0.1-0.10"

["0.2.1-0.2.2"]
LightGraphs = "0.2-0.10"

["0.3"]
julia = "0.4-0.6"

["0.3.2"]
Compat = "0.7.16-0.31"
