["0.1"]
Graphs = "0.2-0.8"

["0.1-0.2"]
julia = "0.3-0.6"
JSON = "0.1-0.16"
Requests = "0.0-0.5"

["0.2"]
Compat = "0.0-0.39"

["0.2.0"]
LightGraphs = "0.1-0.11"

["0.2.1-0.2.2"]
LightGraphs = "0.2-0.11"

["0.3"]
julia = "0.4-0.6"

["0.3.2"]
Compat = "0.7.16-0.39"

["0.4"]
julia = "0.6"
Compat = "0.30-0.39"
