["0.0"]
julia = "0.4-0.6"
Compose = "0.1-0.5"
PyCall = "0.0-1.15"
PyPlot = "1.0-2.3"

["0.0-0.6"]
HDF5 = "0.1-0.8"

["0.5"]
julia = "0.5-0.6"
FixedPointNumbers = "0.3-0.4"

["0.5-0.6"]
Colors = "0.4-0.8"
FileIO = "0.0-0.6"

["0.6"]
julia = "0.6"
FixedPointNumbers = "0.0-0.4"
