["0.1"]
julia = "0.3-0.6"
DataArrays = "0.0-0.6"

["0.1-0.2"]
DataFrames = "0.1-0.10"

["0.2"]
IPNets = "0.1-0.4"

["0.2.0"]
ZipFile = "0.1-0.4"

["0.2.0-0.2.1"]
julia = "0.1-0.6"
Requests = "0.0-0.5"

["0.2.1-0.2.2"]
ZipFile = "0.2.4-0.4"

["0.2.2"]
julia = "0.3-0.6"
Requests = "0.2.4-0.5"
