["0.2"]
julia = "0.5-0.6"
ArgParse = "0.2-0.5"
Combinatorics = "0.0-0.4"
Distributions = "0.1-0.14"
FactCheck = "0.0-0.4"
Iterators = "0.1-0.3"
NPZ = "0.0-0.2"
NullableArrays = "0.0-0.1"
PyCall = "0.0-1.14"
PyPlot = "1.0-2.3"
SymmetricTensors = "0.1"
