["0.0"]
ForwardDiff = "0.0-0.5"

["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.3"]
DiffEqBase = "0.6-1.23"

["0.1"]
ForwardDiff = "0.3-0.5"

["0.1-0.3"]
DiffBase = "0.0-0.3"
NLsolve = "0.1-0.11"

["0.2-0.3"]
julia = "0.6"
ForwardDiff = "0.5"

["0.3"]
OrdinaryDiffEq = "0.0-2.19"
