["0.1.0-0.1.3"]
julia = "0.4-0.6"

["0.1.2-0.1.4"]
LegacyStrings = "0.1-0.3"

["0.1.4"]
julia = "0.4"

["0.2"]
julia = "0.5-0.6"

["0.3"]
Nulls = "0.0-0.1"

["0.3-0.4"]
julia = "0.6"

["0.4"]
Missings = "0.2"
