["0.0"]
OrdinaryDiffEq = "0.0-2.30"

["0.0-0.1"]
AlgebraicDiffEq = "0.0-0.1"
DiffEqBase = "0.0-0.14"
FiniteElementDiffEq = "0.0-0.4"
StochasticDiffEq = "0.0-2.19"

["0.0-0.3"]
ParameterizedFunctions = "0.2-2.3"

["0.0-0.8"]
JLD = "0.6.5-0.8"

["0.0-0.9"]
julia = "0.5-0.6"

["0.2"]
StochasticDiffEq = "0.1-2.19"

["0.2-0.3"]
AlgebraicDiffEq = "0.0.2-0.1"

["0.2-0.4"]
DiffEqBase = "0.2-0.14"
FiniteElementDiffEq = "0.0.5-0.4"

["0.4-0.5"]
ParameterizedFunctions = "0.5-2.3"

["0.4-0.11"]
DiffEqPDEBase = "0.0-0.3"

["0.5-0.9"]
DiffEqBase = "0.15-2.6"

["0.6-0.11"]
ParameterizedFunctions = "2.0-2.3"

["0.10-0.11"]
julia = "0.6"
DiffEqBase = "1.21-2.6"
