["0.0"]
ForwardDiff = "0.1.1-0.1.8"

["0.0-0.1"]
julia = "0.4-0.6"

["0.1-0.2.0"]
ForwardDiff = "0.1.1-0.5"

["0.2"]
julia = "0.5-0.6"

["0.2.1-0.4"]
ForwardDiff = "0.3-0.5"

["0.3-0.4"]
julia = "0.6"
