["0.0"]
Optim = "0.1-0.11"

["0.0-0.1"]
julia = "0.5-0.6"

["0.0-0.2"]
Calculus = "0.1-0.2"
FunctionWrappers = "0.0-0.1"
JSON = "0.1-0.16"
PyAMG = "0.0-0.2"
PyCall = "0.0-1.15"
Reexport = "0.0-0.1"
StaticArrays = "0.0-0.6"

["0.1"]
Dierckx = "0.1-0.3"
Optim = "0.7.5-0.11"

["0.1-0.2"]
LineSearches = "0.0-3.2"

["0.1.1-0.2"]
ForwardDiff = "0.4-0.7"
PositiveFactorizations = "0.0-0.1"

["0.2"]
julia = "0.6"
Dierckx = "0.2.1-0.3"
Optim = "0.10-0.11"
