["0.0"]
Optim = "0.1-0.9"

["0.0-0.1"]
julia = "0.5-0.6"
Calculus = "0.1-0.2"
FunctionWrappers = "0.0-0.1"
JSON = "0.1-0.13"
PyAMG = "0.0-0.2"
PyCall = "0.0-1.14"
Reexport = "0.0"
StaticArrays = "0.0-0.6"

["0.1"]
Dierckx = "0.1-0.2"
LineSearches = "0.0-2.2"
Optim = "0.7.5-0.9"

["0.1.1"]
ForwardDiff = "0.4-0.5"
PositiveFactorizations = "0.0"
