["0.1-0.3"]
julia = "0.2-0.6"

["0.1-0.7"]
BinDeps = "0.0-0.6"
Homebrew = "0.0-0.5"

["0.1.0"]
MathProgBase = "0.1-0.2"

["0.1.1"]
MathProgBase = "0.1-0.6"

["0.2-0.3"]
MathProgBase = "0.3.1-0.6"

["0.4-0.5"]
julia = "0.3-0.6"

["0.4.0"]
MathProgBase = "0.3.6-0.6"

["0.4.1-0.5"]
MathProgBase = "0.3.8-0.6"

["0.4.2-0.5"]
Compat = "0.0-0.33"

["0.6"]
julia = "0.4-0.6"

["0.6.0-0.6.2"]
MathProgBase = "0.4"

["0.6.3-0.6.7"]
MathProgBase = "0.5"

["0.6.6-0.6.7"]
Compat = "0.8.6-0.33"

["0.7"]
julia = "0.5-0.6"
MathProgBase = "0.5-0.6"
