["0.0-0.1.0"]
julia = "0.3-0.6"

["0.0-0.2"]
Winston = "0.3-0.13"

["0.0-0.3.3"]
Grid = "0.1-0.4"

["0.0-0.4"]
Dierckx = "0.1-0.2"
Distributions = "0.1-0.14"
NLopt = "0.0-0.3"
ProgressMeter = "0.0-0.4"

["0.0.3-0.2"]
Cpp = "0.0-0.1"

["0.1.1-0.3"]
julia = "0.4-0.6"

["0.3.4-0.4"]
Interpolations = "0.0-0.6"

["0.4"]
julia = "0.5-0.6"
