["0.1"]
MacroTools = "0.3.3-0.4"

["0.1-0.2"]
julia = "0.5-0.6"
AxisArrays = "0.0-0.2"
Compat = "0.17-0.44"
DataStructures = "0.2-0.7"
Distributions = "0.1-0.15"
Dolang = "0.1-0.2"
NLsolve = "0.1-0.13"
Optim = "0.1-0.11"
QuantEcon = "0.10.1-0.14"
Requests = "0.0-0.5"
YAML = "0.2.1"

["0.2"]
BasisMatrices = "0.3-0.4"
IterativeSolvers = "0.0-0.4"
Iterators = "0.1-0.3"
MacroTools = "0.1-0.4"
StaticArrays = "0.0-0.6"
StringDistances = "0.0-0.2"
