["0.1"]
julia = "0.5-0.6"
AxisArrays = "0.0-0.2"
Compat = "0.17-0.37"
DataStructures = "0.2-0.7"
Distributions = "0.1-0.15"
Dolang = "0.1-0.2"
MacroTools = "0.3.3-0.4"
NLsolve = "0.1-0.13"
Optim = "0.1-0.10"
QuantEcon = "0.10.1-0.14"
Requests = "0.0-0.5"
YAML = "0.2.1"
