["0.1"]
julia = "0.5-0.6"
AxisArrays = "0.0-0.1"
Compat = "0.17-0.31"
DataStructures = "0.2-0.6"
Distributions = "0.1-0.14"
Dolang = "0.1"
MacroTools = "0.3.3-0.3.7"
NLsolve = "0.1-0.11"
Optim = "0.1-0.9"
QuantEcon = "0.10.1-0.13"
Requests = "0.0-0.5"
YAML = "0.2.1"
