["0.0"]
julia = "0.5-0.6"
CategoricalArrays = "0.0.6-0.1"
NullableArrays = "0.0.10-0.1"

["0.0-0.1"]
Compat = "0.9.2-0.37"
StatsBase = "0.11.1-0.19"

["0.0.1"]
DataFrames = "0.8.3-0.10"

["0.0.2"]
DataTables = "0.0"

["0.1"]
julia = "0.6"
CategoricalArrays = "0.3"
DataFrames = "0.11"
Missings = "0.2"
