["0.0-0.1"]
julia = "0.3-0.7"

["0.0-0.2"]
Compat = "0.0-0.49"
FactCheck = "0.0-0.4"

["0.0-0.3"]
Distributions = "0.1-0.15"
StatsBase = "0.1-0.19"

["0.2"]
julia = "0.4-0.7"

["0.3"]
julia = "0.5-0.7"
Compat = "0.18-0.49"
CPUTime = "0.0"
