["0.0"]
FixedPointNumbers = "0.0-0.2"

["0.0-0.3"]
julia = "0.5-0.6"

["0.0-0.4"]
Colors = "0.4-0.8"
Graphics = "0.1-0.2"

["0.0.1-0.0.3"]
MappedArrays = "0.0"

["0.0.4-0.4"]
MappedArrays = "0.0.3-0.0.7"

["0.0.5-0.4"]
OffsetArrays = "0.1-0.3"

["0.0.5-0.4.0"]
ShowItLikeYouBuildIt = "0.0-0.1"

["0.1-0.4"]
FixedPointNumbers = "0.3-0.4"

["0.1.2-0.2.0"]
ColorTypes = "0.0-0.6"

["0.1.3-0.4"]
Compat = "0.19-0.31"

["0.2.1-0.4"]
ColorTypes = "0.4-0.6"

["0.3.1"]
PaddedViews = "0.0-0.1"

["0.3.2-0.4"]
PaddedViews = "0.0.2-0.1"

["0.4"]
julia = "0.6"

["0.4.1"]
ShowItLikeYouBuildIt = "0.1"
