["0.0"]
Clustering = "0.2-0.9"
Distributions = "0.1-0.9"

["0.0.1-0.0.3"]
Compat = "0.0-0.39"
MAT = "0.1-0.4"

["0.0.1-0.0.8"]
julia = "0.1-0.6"
HDF5 = "0.1-0.8"
NumericExtensions = "0.2-0.6"

["0.0.4-0.1"]
PDMats = "0.1-0.7"

["0.0.5-0.1"]
Compat = "0.0-0.39"

["0.0.8-0.1"]
JLD = "0.5-0.8"

["0.0.9-0.0.12"]
julia = "0.3-0.6"

["0.0.12-0.1"]
ScikitLearnBase = "0.0.2-0.3"

["0.1"]
julia = "0.4-0.6"
Clustering = "0.6-0.9"
Distributions = "0.1-0.15"
