["0.1"]
julia = "0.5-0.6"

["0.1-0.2.1"]
DataFlow = "0.1-0.2.0"
Iterators = "0.1-0.3"

["0.1-0.3"]
Juno = "0.1-0.3"

["0.2-0.3"]
julia = "0.6"
MacroTools = "0.3.3-0.3.7"

["0.2.2"]
DataFlow = "0.2.1"

["0.3"]
DataFlow = "0.2.1-0.3"
ForwardDiff = "0.0-0.6"
NNlib = "0.1"
Requires = "0.1-0.4"
