["0.0-0.2"]
Compat = "0.0-0.37"
DataFrames = "0.1-0.10"
NLopt = "0.0-0.3"

["0.0.1"]
julia = "0.3-0.6"

["0.0.1-0.0.2"]
GraphViz = "0.0-0.1"

["0.0.2-0.3"]
julia = "0.4-0.6"

["0.0.3-0.2"]
Gadfly = "0.1-0.6"
GLM = "0.2-0.8"

["0.1-0.2"]
ColorTypes = "0.0-0.6"
StatsBase = "0.1-0.19"

["0.3-0.5"]
Compat = "0.8-0.37"

["0.3-0.5.0"]
DataFrames = "0.7-0.10"
StatsBase = "0.9-0.19"

["0.3-0.6"]
ColorTypes = "0.2-0.6"
Gadfly = "0.4-0.6"
GLM = "0.5-0.8"
NLopt = "0.3"

["0.4-0.5"]
julia = "0.5-0.6"
Combinatorics = "0.3-0.5"

["0.5.1-0.6"]
DataFrames = "0.9-0.10"
StatsBase = "0.11-0.19"

["0.6"]
julia = "0.6"
Combinatorics = "0.2.1-0.5"
DataStructures = "0.5.2-0.7"
RCall = "0.6.1-0.8"
