["0.0"]
julia = "0.5-0.6"
ApproxFun = "0.6-0.7"

["0.0-0.1"]
BandedMatrices = "0.2-0.3"
DualNumbers = "0.3"
IntervalSets = "0.0.2-0.1"
StaticArrays = "0.3-0.6"

["0.1"]
julia = "0.6"
ApproxFun = "0.7"
Compat = "0.31-0.37"
