["0.1"]
julia = "0.1"

["0.1-0.2"]
Distributions = "0.1-0.14"

["0.2.0"]
Rmath = "0.1-0.3"

["0.2.0-0.2.2"]
julia = "0.2-0.6"

["0.2.3-0.2.9"]
julia = "0.1-0.6"

["0.2.8-0.6"]
Roots = "0.1-0.4"

["0.2.10"]
julia = "0.3-0.6"
Compat = "0.0-0.31"
StatsBase = "0.1-0.18"

["0.3-0.4"]
julia = "0.4-0.6"
Compat = "0.8.4-0.31"

["0.3-0.6"]
Combinatorics = "0.0-0.4"
Distributions = "0.10-0.14"
Rmath = "0.1.2-0.3"
StatsBase = "0.9-0.18"

["0.5"]
julia = "0.5-0.6"

["0.5-0.6"]
Compat = "0.18-0.31"

["0.6"]
julia = "0.6"
