["0.0-0.2"]
julia = "0.5-0.6"

["0.0-0.3"]
DataStructures = "0.2-0.6"
MacroTools = "0.1-0.3"
Matcha = "0.0-0.1"

["0.0.2-0.3"]
Compat = "0.17-0.31"

["0.1-0.3"]
StaticArrays = "0.3-0.6"

["0.3"]
julia = "0.6"
