["0.0-0.2"]
julia = "0.5-0.6"

["0.0-0.4"]
DataStructures = "0.2-0.7"
MacroTools = "0.1-0.4"

["0.0-0.4.0"]
Matcha = "0.0-0.1"

["0.0.2-0.4"]
Compat = "0.17-0.37"

["0.1-0.4"]
StaticArrays = "0.3-0.6"

["0.3-0.4"]
julia = "0.6"

["0.4.1"]
Matcha = "0.1.1"
