["0.0"]
julia = "0.4-0.6"

["0.0-0.1"]
Plots = "0.0-0.12"

["0.0-0.4"]
DataFrames = "0.1-0.10"
Distributions = "0.1-0.14"
KernelDensity = "0.0-0.3"
Reexport = "0.0"
StatsBase = "0.1-0.18"

["0.1-0.3"]
julia = "0.5-0.6"

["0.2-0.3"]
Plots = "0.10-0.12"

["0.3-0.4"]
Loess = "0.0-0.3"

["0.4"]
julia = "0.6"
Plots = "0.12"
