["0.0-0.1"]
julia = "0.3-0.7"
Clustering = "0.2-0.9"
DataFrames = "0.1-0.10"
Dates = "0.7"
Distances = "0.1-0.5"
Distributions = "0.1-0.15"
Gadfly = "0.1-0.6"
HDF5 = "0.1-0.8"
PyPlot = "1.0-2.3"
QuantEcon = "0.0-0.14"
StatsBase = "0.1-0.20"
