["0.0-0.1"]
julia = "0.5-0.6"

["0.0.1-0.0.2"]
Calculus = "0.1.15-0.2"
DiffBase = "0.0.2-0.2"
ForwardDiff = "0.3.2-0.4"

["0.0.3-0.1"]
ForwardDiff = "0.3.4-0.4"

["0.0.3-0.1.2"]
Calculus = "0.2"

["0.0.3-0.1.4"]
DiffBase = "0.0.3-0.2"

["0.1"]
Compat = "0.19-0.31"

["0.1.4-0.1.5"]
FunctionWrappers = "0.1"

["0.1.5"]
DiffBase = "0.0.3-0.3"
