["0.0-0.1.1"]
Reactive = "0.3-0.6"

["0.0-0.2"]
julia = "0.5-0.6"
Cairo = "0.0-0.3"
Colors = "0.4-0.8"
Compat = "0.17-0.31"
Gtk = "0.13"
IntervalSets = "0.0.5-0.1"
Reexport = "0.0"
RoundingIntegers = "0.0"

["0.0.1-0.0.3"]
Graphics = "0.1-0.2"

["0.0.2-0.2"]
FixedPointNumbers = "0.3-0.4"

["0.0.4-0.2"]
Graphics = "0.2"

["0.1.2-0.2"]
Reactive = "0.4-0.6"
