["0.0"]
julia = "0.5-0.6"
Colors = "0.4-0.8"
ColorTypes = "0.0-0.6"
CoordinateTransformations = "0.1-0.4"
Gadfly = "0.1-0.6"
GeometryTypes = "0.0-0.4"
HDF5 = "0.1-0.8"
JLD = "0.5-0.8"
JSON = "0.1-0.13"
Rotations = "0.0-0.6"

["0.0.1-0.0.2"]
DrakeVisualizer = "0.0-0.2"
Graphs = "0.2-0.7"
IncrementalInference = "0.0-0.2"
KernelDensityEstimate = "0.0-0.2"
RoME = "0.0"

["0.0.1-0.0.3"]
TransformUtils = "0.0"

["0.0.2-0.0.5"]
FileIO = "0.0-0.5"
MeshIO = "0.0-0.1"
NLsolve = "0.1-0.11"

["0.0.3"]
IncrementalInference = "0.2.5-0.2.9"
KernelDensityEstimate = "0.2.3-0.2.4"
RoME = "0.0.4-0.0.7"

["0.0.3-0.0.5"]
DataStructures = "0.2-0.7"
Distributions = "0.1-0.14"
DrakeVisualizer = "0.1.2-0.2"
Graphs = "0.7.1"
ProgressMeter = "0.0-0.4"

["0.0.4"]
RoME = "0.0.6-0.0.7"

["0.0.4-0.0.5"]
ImageCore = "0.0-0.4"
ImageMagick = "0.0-0.5"
IncrementalInference = "0.2.8-0.2.9"
KernelDensityEstimate = "0.2.4"
PyLCM = "0.0-0.1"
TransformUtils = "0.0.6"

["0.0.5"]
CloudGraphs = "0.0"
LibBSON = "0.0-0.3"
Mongo = "0.2.3-0.3"
Neo4j = "1.0"
PyCall = "0.0-1.14"
RoME = "0.0.5-0.0.7"
