["0.0-0.2"]
DiffEqBase = "0.0-0.4"
SymEngine = "0.1.1-0.3"

["0.0-2.2"]
julia = "0.5-0.7"

["0.0-3.0"]
DataStructures = "0.4.6-0.7"

["0.3-1.3"]
SymEngine = "0.1.2-0.3"

["0.3.0-0.3.2"]
DiffEqBase = "0.1-0.4"

["0.3.3-0.4"]
DiffEqBase = "0.2-0.4"

["0.4-3.0"]
SimpleTraits = "0.1.1-0.5"

["0.5"]
DiffEqBase = "0.4"

["0.6-1.2"]
DiffEqBase = "0.5-0.13"

["1.3-2.3"]
DiffEqBase = "0.14-2.10"

["2.0"]
Iterators = "0.1-0.3"

["2.0-3.0"]
SymEngine = "0.2-0.3"

["2.3-3.0"]
julia = "0.6-0.7"

["3.0"]
DiffEqBase = "0.14-3.0"
