["0.1-0.2"]
julia = "0.4-0.6"

["0.1-0.3"]
Iterators = "0.1-0.3"

["0.1-0.4"]
Distributions = "0.1-0.14"
Interpolations = "0.0-0.6"
ProgressMeter = "0.0-0.4"

["0.1.0-0.1.1"]
Clp = "0.0-0.3"
FactCheck = "0.0-0.4"
JuMP = "0.1-0.15"
MathProgBase = "0.1-0.6"

["0.1.2-0.2"]
JuMP = "0.13-0.15"

["0.3"]
JuMP = "0.16-0.18"

["0.3-0.4"]
julia = "0.5-0.6"

["0.4"]
Compat = "0.18-0.31"
CutPruners = "0.0.2"
JuMP = "0.17-0.18"
