["0.2"]
julia = "0.6"
ArgParse = "0.2-0.5"
ColorBrewer = "0.1-0.3"
Compat = "0.17-0.44"
DataFrames = "0.1-0.11"
Distributions = "0.1-0.15"
Gadfly = "0.1-0.6"
HypothesisTests = "0.1-0.6"
IterTools = "0.1-0.2"
StatsBase = "0.1-0.19"
YAML = "0.1-0.2"
