["0.0"]
julia = "0.5-0.6"

["0.0-0.1"]
DocOpt = "0.0-0.2"
EnglishText = "0.1-0.5"
Mustache = "0.0-0.3"
PkgDev = "0.1"

["0.1"]
julia = "0.6"
DataStructures = "0.2-0.7"
Documenter = "0.1-0.12"
Revise = "0.0-0.1"
TestSetExtensions = "0.0-1.0"
