["0.2-0.3"]
Conda = "0.1-0.7"
PyCall = "0.0-1.14"

["0.2-0.3.0"]
Images = "0.2-0.11"

["0.2-0.4"]
julia = "0.5-0.6"

["0.2-0.5"]
ArgParse = "0.2-0.5"
Colors = "0.4-0.8"
DataStructures = "0.2-0.6"
DSP = "0.0-0.3"
FileIO = "0.0-0.5"
Juno = "0.1-0.3"
Lazy = "0.1-0.11"
SampledSignals = "0.0-1.0"

["0.2.0"]
Reactive = "0.1-0.6"

["0.2.0-0.2.1"]
LibSndFile = "0.2-1.0"

["0.2.1-0.5"]
Homebrew = "0.0-0.5"

["0.2.4-0.5"]
LibSndFile = "0.2-1.0"

["0.3-0.5"]
MacroTools = "0.1-0.3"

["0.3.1-0.5"]
Distributions = "0.1-0.14"
FixedPointNumbers = "0.3-0.4"
Images = "0.6-0.11"

["0.4-0.5"]
LRUCache = "0.0"

["0.5"]
julia = "0.6"
IntervalSets = "0.0-0.1"
Unitful = "0.0-0.2"
