["0.0"]
DiffEqBase = "0.5-0.6"
OrdinaryDiffEq = "1.0-1.1"
RecursiveArrayTools = "0.1.2-0.12"

["0.0-0.4"]
julia = "0.5-0.6"

["0.0-0.10"]
Combinatorics = "0.0-0.4"

["0.0-1.0"]
DataStructures = "0.4.6-0.7"

["0.1"]
OrdinaryDiffEq = "1.2-2.14"

["0.1-0.2"]
DiffEqBase = "0.8-0.14"

["0.1-1.0"]
RecursiveArrayTools = "0.2-0.12"

["0.2-0.4"]
OrdinaryDiffEq = "1.6-2.14"

["0.3-0.5.0"]
DiffEqBase = "0.15-1.23"

["0.4-0.10"]
Compat = "0.17-0.31"

["0.5-1.0"]
julia = "0.6"
Reexport = "0.0"

["0.5.0"]
OrdinaryDiffEq = "2.9-2.14"

["0.5.1-0.5.2"]
DiffEqBase = "1.15-1.23"

["0.5.1-0.6"]
OrdinaryDiffEq = "2.10-2.14"

["0.6-0.9"]
DiffEqBase = "1.16-1.23"

["0.6-1.0"]
MuladdMacro = "0.0"

["0.7-0.8"]
OrdinaryDiffEq = "2.13-2.14"

["0.9"]
OrdinaryDiffEq = "2.15-2.18"

["0.10"]
DiffEqBase = "1.21-1.23"
OrdinaryDiffEq = "2.17-2.18"

["1.0"]
DiffEqBase = "1.23"
ForwardDiff = "0.0-0.5"
NLsolve = "0.1-0.11"
OrdinaryDiffEq = "2.19"
Roots = "0.1-0.4"
