["0.0"]
GLM = "0.2-0.7"
StatsBase = "0.3-0.18"

["0.0-0.1"]
julia = "0.3-0.6"

["0.0-0.1.0"]
Distances = "0.1.1-0.5"

["0.0-0.2"]
DataFrames = "0.6-0.7.6"

["0.0-0.3.0"]
DataArrays = "0.0-0.6"

["0.0-0.4"]
Distributions = "0.6-0.14"

["0.1-0.4"]
StatsBase = "0.7.1-0.18"

["0.1.1-0.3.0"]
Compat = "0.0-0.31"

["0.2"]
julia = "0.4-0.6"

["0.3"]
julia = "0.5-0.6"

["0.3.0"]
DataFrames = "0.6-0.7"

["0.3.1-0.4"]
DataArrays = "0.3.4-0.6"
DataFrames = "0.9-0.10"

["0.4"]
julia = "0.6"
