["0.0"]
julia = "0.5-0.6"

["0.0-0.1"]
BinDeps = "0.0-0.6"

["0.0.1"]
Polyhedra = "0.1.1"

["0.0.2"]
Polyhedra = "0.1.2"

["0.0.2-0.1"]
Homebrew = "0.0-0.5"

["0.0.3-0.0.6"]
Polyhedra = "0.1.3-0.1.5"

["0.1"]
julia = "0.6"

["0.1.0"]
Polyhedra = "0.2"

["0.1.1-0.1.2"]
Polyhedra = "0.2.1-0.2.2"
