["0.0-0.1"]
IterableTables = "0.2-0.4"

["0.0-0.2"]
julia = "0.6"
DataFrames = "0.9-0.10"
DataTables = "0.0.3"
DataValues = "0.1-0.2"
ExcelReaders = "0.7-0.8"
FileIO = "0.4-0.5"

["0.2"]
IterableTables = "0.5"
TableTraits = "0.0"
