["0.0-0.1"]
julia = "0.6"
DataStructures = "0.4.5-0.7"
NamedTuples = "3.0.2-4.0"

["0.0-0.1.0"]
DataValues = "0.0.2-0.3"

["0.0.1"]
TableTraits = "0.0"

["0.0.2-0.1"]
IteratorInterfaceExtensions = "0.0"
