["0.0"]
julia = "0.3-0.6"
ColorTypes = "0.0-0.6"
Compat = "0.0-0.31"
FixedPointNumbers = "0.0-0.2"

["0.1"]
julia = "0.4-0.6"

["0.1.0-0.1.8"]
ColorTypes = "0.2-0.6"
FixedPointNumbers = "0.1-0.2"

["0.1.8-0.3.0"]
Compat = "0.9.1-0.31"

["0.1.9-0.1.12"]
ColorTypes = "0.2.7-0.6"
FixedPointNumbers = "0.1.8-0.2"

["0.2"]
ColorTypes = "0.3-0.6"

["0.2-0.4"]
julia = "0.5-0.6"
FixedPointNumbers = "0.3-0.4"

["0.3-0.4"]
Colors = "0.7.1-0.8"
StatsBase = "0.8.2-0.18"

["0.3-0.4.0"]
ColorTypes = "0.3.3-0.6"

["0.3.1-0.4"]
Compat = "0.18-0.31"

["0.4.1-0.4.4"]
ColorTypes = "0.4-0.6"
