["0.0-0.1"]
julia = "0.3-0.4"
Graphs = "0.2-0.7"

["0.0-1.0.2"]
DataFrames = "0.1-0.10"

["0.0.2-1.0.2"]
TikzGraphs = "0.0-0.5"

["0.2"]
julia = "0.3-0.6"

["0.2-1.0.2"]
LightGraphs = "0.1-0.10"
LightXML = "0.1-0.5"

["0.3-1.0"]
julia = "0.4-0.6"

["0.4-1.0.2"]
Reexport = "0.0"

["1.0.0-1.0.2"]
Compat = "0.0-0.31"
Discretizers = "0.0-2.1"
Distributions = "0.1-0.14"
Iterators = "0.1-0.3"

["1.0.3-1.0.4"]
Compat = "0.8-0.31"
Distributions = "0.10-0.14"

["1.0.3-2.1"]
DataFrames = "0.8-0.10"
Discretizers = "0.3-2.1"
Iterators = "0.1.9-0.3"
LightGraphs = "0.6-0.10"
LightXML = "0.3-0.5"
Reexport = "0.0.3"
TikzGraphs = "0.1.1-0.5"

["1.0.5"]
Compat = "0.9.2-0.31"

["1.0.5-2.1"]
Distributions = "0.11-0.14"

["2.0-2.1"]
julia = "0.6"
DataStructures = "0.5-0.7"
Parameters = "0.5-0.7"
