["0.0"]
julia = "0.6-0.7"
DiffEqCallbacks = "1.0"
DocStringExtensions = "0.4.1-0.4.3"
LoopThrottle = "0.0"
OrdinaryDiffEq = "3.0.1-3.1"
Reexport = "0.1"
RigidBodyDynamics = "0.4"
RigidBodyTreeInspector = "0.3.2-0.3.3"
