["0.0-0.1"]
ImageCore = "0.0-0.5"

["0.0-0.3"]
julia = "0.5-0.6"

["0.0-0.4"]
AxisArrays = "0.0-0.2"
Colors = "0.4-0.8"
Reexport = "0.0"
SimpleTraits = "0.1-0.5"

["0.1-0.4"]
FixedPointNumbers = "0.3-0.4"

["0.2-0.4"]
ImageCore = "0.2-0.5"
MappedArrays = "0.0"

["0.3-0.4"]
Compat = "0.17-0.39"

["0.4"]
julia = "0.6"
