["0.0-0.1"]
ImageCore = "0.0-0.4"

["0.0-0.3"]
julia = "0.5-0.6"
AxisArrays = "0.0-0.1"
Colors = "0.4-0.8"
Reexport = "0.0"
SimpleTraits = "0.1-0.5"

["0.1-0.3"]
FixedPointNumbers = "0.3-0.4"

["0.2-0.3"]
ImageCore = "0.2-0.4"
MappedArrays = "0.0"

["0.3"]
Compat = "0.17-0.31"
