["0.0"]
julia = "0.4-0.6"
Requests = "0.0-0.5"

["0.0-0.1"]
DataFrames = "0.1-0.10"
DataStructures = "0.2-0.7"

["0.0.3"]
Compat = "0.7.9-0.31"

["0.0.3-0.1"]
DocStringExtensions = "0.1-0.4"

["0.1"]
julia = "0.5-0.6"
HTTP = "0.0-0.4"
JSON = "0.1-0.13"
