["0.0-1.0"]
UUID = "0.0-0.1"

["0.0.1-0.0.3"]
julia = "0.2-0.6"
Datetime = "0.1"

["0.0.4"]
julia = "0.4-0.6"

["0.0.5-1.0"]
julia = "0.3-0.6"
Compat = "0.0-0.31"
Dates = "0.0-0.4"

["0.0.7-2.1"]
JSON = "0.1-0.13"

["2.0-2.1"]
julia = "0.4-0.6"

["2.0.0"]
StackTraces = "0.0-0.1"

["2.0.1-2.1"]
StackTraces = "0.1"

["2.1"]
Mocking = "0.0-0.3"

["2.1.1"]
Compat = "0.17-0.31"
