["0.1"]
julia = "0.5-0.6"
POMDPs = "0.1-0.6"

["0.1-0.2"]
Distributions = "0.1-0.14"
POMDPToolbox = "0.1-0.2"
TikzPictures = "0.0-1.2"

["0.1.2-0.2"]
AutoHashEquals = "0.0-0.1"

["0.1.3-0.2"]
StaticArrays = "0.0-0.6"
StatsBase = "0.15-0.18"

["0.2"]
julia = "0.6"
POMDPs = "0.6"
