["0.0"]
julia = "0.2-0.7"

["0.0-0.4"]
OpenCL = "0.0-0.7"

["0.0.1-0.0.2"]
FactCheck = "0.0-0.4"

["0.1"]
julia = "0.3-0.7"

["0.2"]
julia = "0.4-0.7"

["0.3-0.5"]
julia = "0.5-0.7"
Primes = "0.1-0.2"

["0.4-0.5"]
BinDeps = "0.0-0.8"

["0.5"]
Compat = "0.9.1-0.49"
OpenCL = "0.6-0.7"

["0.5.1"]
Homebrew = "0.0-0.6"
