["0.0"]
julia = "0.2-0.6"

["0.0-0.4"]
OpenCL = "0.0-0.6"

["0.0.1-0.0.2"]
FactCheck = "0.0-0.4"

["0.1"]
julia = "0.3-0.6"

["0.2"]
julia = "0.4-0.6"

["0.3-0.5"]
julia = "0.5-0.6"
Primes = "0.1"

["0.4-0.5"]
BinDeps = "0.0-0.6"

["0.5"]
Compat = "0.9.1-0.31"
OpenCL = "0.6"
