["0.0"]
julia = "0.6-0.7"
GZip = "0.1-0.3"
Logging = "0.0-0.3"

["0.0.1"]
IterativeSolvers = "0.0-0.4"
LightGraphs = "0.1-0.11"
PyAMG = "0.0-0.2"

["0.0.2"]
AMG = "0.0.2-0.0.3"
IterativeSolvers = "0.4.1-0.4.2"
LightGraphs = "0.11"
SimpleWeightedGraphs = "0.3"
