["0.0"]
julia = "0.6"
IndexedTables = "0.3.2-0.3.3"
IterableTables = "0.5.1-0.5.2"
KernelDensity = "0.0-0.3"
Lazy = "0.1-0.12"
Loess = "0.0-0.3"
MacroTools = "0.1-0.3"
StatsBase = "0.1-0.19"
TableTraits = "0.0"
TableTraitsUtils = "0.1"
