["0.1"]
julia = "0.5-0.6"

["0.1-0.3"]
Compat = "0.19-0.33"
NamedTuples = "2.1-4.0"
PooledArrays = "0.0-0.1"

["0.2-0.3"]
julia = "0.6"

["0.3.2-0.3.3"]
TableTraits = "0.0"
TableTraitsUtils = "0.0-0.1"
