["0.1"]
julia = "0.5-0.6"

["0.1-0.5"]
Compat = "0.19-0.44"
NamedTuples = "2.1-4.0"
PooledArrays = "0.0-0.1"

["0.2-0.5"]
julia = "0.6"

["0.3.2-0.5"]
TableTraits = "0.0-0.1"
TableTraitsUtils = "0.0-0.1"

["0.4-0.5"]
OnlineStats = "0.13-0.14"
