["0.0"]
Languages = "0.0-0.2"

["0.0-0.2"]
DataFrames = "0.1-0.10"

["0.0.1"]
julia = "0.2-0.6"

["0.0.2"]
julia = "0.1-0.6"

["0.0.2-0.2"]
BinDeps = "0.0-0.6"

["0.0.3-0.0.5"]
julia = "0.3-0.6"

["0.0.4-0.0.5"]
Compat = "0.0-0.37"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8.8-0.37"
Languages = "0.1-0.2"

["0.2"]
julia = "0.5-0.6"
Compat = "0.17-0.37"
Languages = "0.2"
