["0.0-0.4"]
julia = "0.5-0.6"

["0.0.1"]
DiffEqBase = "0.0-0.13"
LossFunctions = "0.0-0.2"
LsqFit = "0.0-0.3"
OrdinaryDiffEq = "0.0-2.19"
RecursiveArrayTools = "0.0-0.12"

["0.0.2"]
OrdinaryDiffEq = "0.1.1-2.19"

["0.0.2-0.1"]
DiffEqBase = "0.1.2-0.13"

["0.0.2-0.5"]
RecursiveArrayTools = "0.0.2-0.12"

["0.0.2-0.6"]
LossFunctions = "0.0.2-0.2"
LsqFit = "0.0.2-0.3"

["0.1-0.6"]
Calculus = "0.1-0.2"
ForwardDiff = "0.0-0.6"

["0.2-0.3"]
DiffEqBase = "0.14-1.23"

["0.2-0.6"]
Compat = "0.17-0.33"
Optim = "0.1-0.9"

["0.4-0.6"]
DiffEqBase = "1.7-1.23"

["0.5-0.6"]
julia = "0.6"

["0.6"]
PenaltyFunctions = "0.0"
RecursiveArrayTools = "0.10-0.12"
