["0.0-0.4"]
julia = "0.5-0.6"

["0.0.1"]
DiffEqBase = "0.0-0.13"
LossFunctions = "0.0-0.2"
LsqFit = "0.0-0.3"
OrdinaryDiffEq = "0.0-2.35"
RecursiveArrayTools = "0.0-0.14"

["0.0.2"]
OrdinaryDiffEq = "0.1.1-2.35"

["0.0.2-0.1"]
DiffEqBase = "0.1.2-0.13"

["0.0.2-0.5"]
RecursiveArrayTools = "0.0.2-0.14"

["0.0.2-0.7"]
LossFunctions = "0.0.2-0.2"
LsqFit = "0.0.2-0.3"

["0.1-0.7"]
Calculus = "0.1-0.2"
ForwardDiff = "0.0-0.7"

["0.2-0.3"]
DiffEqBase = "0.14-2.10"

["0.2-0.6"]
Compat = "0.17-0.44"

["0.2-0.7"]
Optim = "0.1-0.11"

["0.4-0.7"]
DiffEqBase = "1.7-2.10"

["0.5-0.7"]
julia = "0.6"

["0.6-0.7"]
PenaltyFunctions = "0.0"
RecursiveArrayTools = "0.10-0.14"
