["0.0-0.1"]
julia = "0.4-0.6"
NLSolversBase = "0.0-2.1"

["1.0"]
NLSolversBase = "1.0"

["1.0-2.1"]
julia = "0.5-0.6"

["2.0-2.2"]
NLSolversBase = "2.0-2.1"

["2.1-3.0"]
Parameters = "0.0-0.8"

["2.2-3.0"]
julia = "0.6"

["3.0"]
NLSolversBase = "3.0-3.1"
