["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.44"
MathProgBase = "0.3"

["0.0-0.2"]
BinDeps = "0.0-0.8"
Cbc = "0.0-0.3"
Clp = "0.0-0.3"
Homebrew = "0.0-0.6"
Ipopt = "0.1-0.2"
WinRPM = "0.1-0.3"

["0.0.1-0.0.3"]
LightXML = "0.1-0.5"

["0.0.4-0.0.5"]
LightXML = "0.1.10-0.5"

["0.0.6-0.2"]
LightXML = "0.2-0.5"

["0.1"]
julia = "0.4-0.6"

["0.1.0"]
MathProgBase = "0.4"

["0.1.1"]
MathProgBase = "0.5"

["0.1.2"]
MathProgBase = "0.5-0.6"

["0.2"]
julia = "0.5-0.6"
MathProgBase = "0.5-0.7"
