["0.0"]
julia = "0.6"
ClobberingReload = "0.2.1"
DataStructures = "0.2-0.7"
MacroTools = "0.3.3-0.3.7"
Memoize = "0.1-0.2"
Requires = "0.1-0.4"

["0.0.1"]
Revise = "0.0.4-0.0.8"

["0.0.2-0.0.6"]
Revise = "0.0.6-0.0.8"

["0.0.3-0.0.6"]
Crayons = "0.0-0.3"
