["0.0.1"]
julia = "0.1-0.7"

["0.0.2-0.0.5"]
julia = "0.3-0.7"

["0.0.2-0.3"]
DataStructures = "0.2-0.7"

["0.0.3-0.0.5"]
Compat = "0.0-0.54"

["0.1"]
julia = "0.4-0.7"

["0.2"]
julia = "0.5-0.7"

["0.3"]
julia = "0.6-0.7"
