["0.2"]
FileIO = "0.0-0.6"
SampledSignals = "0.0-1.1"

["0.2-0.4"]
FixedPointNumbers = "0.0-0.4"
SIUnits = "0.0-0.1"

["0.2-0.5"]
julia = "0.4-0.5"

["0.2-1.0"]
BinDeps = "0.0-0.8"
Homebrew = "0.0-0.6"
WinRPM = "0.1-0.3"

["0.3"]
SampledSignals = "0.1-1.1"

["0.3-1.0"]
FileIO = "0.1.1-0.6"

["0.4"]
SampledSignals = "0.2-1.1"

["0.4-0.5"]
Compat = "0.8.8-0.49"

["0.5"]
SampledSignals = "0.3-1.1"

["1.0"]
julia = "0.6-0.7"
SampledSignals = "1.0-1.1"
