["0.0-0.1.0"]
FactCheck = "0.0-0.4"

["0.0-0.3"]
julia = "0.4-0.6"

["0.0-0.7"]
Colors = "0.4-0.8"

["0.0-0.9.0"]
JSON = "0.1-0.8"

["0.2-0.12"]
Reexport = "0.0"

["0.4"]
julia = "0.3-0.6"

["0.4-0.9.3"]
Compat = "0.0-0.31"

["0.5-0.8"]
julia = "0.4-0.6"

["0.5.2-0.6"]
Requires = "0.1-0.4"

["0.5.3-0.12.0"]
FixedSizeArrays = "0.0-0.2"

["0.6.2"]
RecipesBase = "0.0.1"

["0.7-0.11"]
RecipesBase = "0.0-0.2"

["0.7-0.12"]
Measures = "0.0-0.1"

["0.8-0.10"]
PlotUtils = "0.0-0.4"

["0.8.1-0.12"]
Showoff = "0.0-0.1"

["0.9-0.11"]
julia = "0.5-0.6"

["0.10"]
PlotThemes = "0.0-0.1"

["0.11-0.12"]
PlotThemes = "0.1.3-0.1.4"
PlotUtils = "0.4"
StatsBase = "0.14-0.19"

["0.11.3-0.12"]
FixedPointNumbers = "0.3-0.4"
JSON = "0.1-0.14"
NaNMath = "0.0-0.2"

["0.12"]
julia = "0.6"
RecipesBase = "0.2"

["0.12.1-0.12.4"]
Contour = "0.0-0.4"
Requires = "0.1-0.4"
StaticArrays = "0.5-0.6"
