["0.0"]
julia = "0.5-0.6"
CLBLAS = "1.1"
CLFFT = "0.4-0.5"
Compat = "0.19-0.31"
CUBLAS = "0.0-0.2"
CUDArt = "0.0-0.3"
CUFFT = "0.0"
Matcha = "0.0-0.1"
OpenCL = "0.5.2-0.6"
StaticArrays = "0.0-0.6"
Sugar = "0.0.3-0.3"
Transpiler = "0.0-0.3"

["0.0.2"]
ColorTypes = "0.0-0.6"
