["0.1"]
julia = "0.4-0.7"
Images = "0.5-0.10"

["0.1-0.2"]
PyPlot = "2.0-2.3"

["0.1.2"]
Compat = "0.8.7-0.53"
Interpolations = "0.0-0.7"

["0.2"]
julia = "0.5-0.7"
ImageFiltering = "0.1-0.2"
Images = "0.10-0.12"
Interpolations = "0.4-0.7"
Pkg = "0.7"
