["0.1"]
julia = "0.4-0.6"
Images = "0.5-0.10"

["0.1-0.2"]
PyPlot = "2.0-2.3"

["0.1.2"]
Compat = "0.8.7-0.33"
Interpolations = "0.0-0.7"

["0.2"]
julia = "0.5-0.6"
ImageFiltering = "0.1-0.2"
Images = "0.10-0.11"
Interpolations = "0.4-0.7"
