["0.1"]
julia = "0.3-0.6"
Docile = "0.4.5-0.5"

["0.1-0.2.0"]
Optim = "0.3-0.4"

["0.1.2-0.5"]
PDMats = "0.3-0.7"

["0.1.3-0.3"]
ArrayViews = "0.6"

["0.1.3-0.5"]
Distances = "0.2-0.5"

["0.2-0.3"]
julia = "0.4-0.6"

["0.2-0.5"]
ScikitLearnBase = "0.0-0.3"

["0.2.1"]
Optim = "0.3-0.10"

["0.3-0.4"]
Optim = "0.5-0.10"

["0.4"]
julia = "0.5-0.6"

["0.4-0.5"]
Compat = "0.9.2-0.37"

["0.5"]
julia = "0.6"
FastGaussQuadrature = "0.1-0.3"
Klara = "0.9.2"
Optim = "0.7-0.10"
RecipesBase = "0.1-0.2"
