["0.1"]
julia = "0.3-0.6"
Docile = "0.4.5-0.5"

["0.1-0.2.0"]
Optim = "0.3-0.4"

["0.1.2-0.4"]
PDMats = "0.3-0.7"

["0.1.3-0.3"]
ArrayViews = "0.6"

["0.1.3-0.4"]
Distances = "0.2-0.5"

["0.2-0.3"]
julia = "0.4-0.6"

["0.2-0.4"]
ScikitLearnBase = "0.0-0.3"

["0.2.1"]
Optim = "0.3-0.9"

["0.3-0.4"]
Optim = "0.5-0.9"

["0.4"]
julia = "0.5-0.6"
Compat = "0.9.2-0.33"
