["0.1-0.3"]
Compat = "0.0-0.37"
Dates = "0.0-0.4"
Docile = "0.0-0.5"
Reexport = "0.0"

["0.1-0.4"]
MultivariateStats = "0.0-0.4"

["0.1-0.9"]
Distributions = "0.1-0.15"

["0.1-0.11"]
StatsBase = "0.1-0.19"

["0.1.0"]
Clustering = "0.2-0.9"
Convex = "0.0-0.5"
SCS = "0.0-0.3"

["0.1.0-0.1.1"]
julia = "0.1-0.6"
FactCheck = "0.0-0.4"
GLM = "0.2-0.8"

["0.1.1"]
Reactive = "0.1-0.6"

["0.1.2-0.2"]
julia = "0.3-0.6"

["0.3-0.6"]
julia = "0.4-0.6"

["0.4-0.5"]
Requires = "0.1-0.4"

["0.5"]
ArrayViews = "0.1-0.6"

["0.6-0.7"]
RecipesBase = "0.0-0.2"

["0.7"]
julia = "0.5-0.6"

["0.7.1-0.11"]
LearnBase = "0.0-0.1"

["0.8-0.13"]
julia = "0.6"

["0.9"]
OnlineStatsBase = "0.0.3-0.2"

["0.9-0.13"]
LossFunctions = "0.0-0.2"
PenaltyFunctions = "0.0"
RecipesBase = "0.0-0.2"
SweepOperator = "0.0-0.1"

["0.10.0"]
OnlineStatsBase = "0.0.5-0.2"

["0.10.1-0.11.0"]
OnlineStatsBase = "0.0.6-0.2"

["0.11.1"]
OnlineStatsBase = "0.0.8-0.2"

["0.12"]
OnlineStatsBase = "0.1-0.2"

["0.12-0.13"]
Reexport = "0.0"

["0.13"]
OnlineStatsBase = "0.2"
