["0.0"]
DataFrames = "0.1-0.10"

["0.0-0.2"]
Distributions = "0.1-0.14"

["0.0.1-0.0.4"]
julia = "0.1-0.6"

["0.0.4-0.0.5"]
Compat = "0.0-0.31"

["0.0.5"]
julia = "0.3-0.6"

["0.2"]
julia = "0.4-0.6"
Compat = "0.9.3-0.31"
StatsBase = "0.1-0.19"
