["0.0-0.2.0"]
RecipesBase = "0.1-0.2"

["0.0-0.3"]
ForwardDiff = "0.2.4-0.5"

["0.0-0.4"]
julia = "0.5-0.6"
ChunkedArrays = "0.1"
GenericSVD = "0.0.2-0.1"
IterativeSolvers = "0.2.2-0.4"
NLsolve = "0.7.3-0.11"
Parameters = "0.5-0.7"
VectorizedRoutines = "0.0.2"

["0.0.1-0.0.3"]
Plots = "0.9.2-0.12"

["0.0.1-0.0.4"]
DiffEqBase = "0.0-0.14"

["0.0.5"]
DiffEqBase = "0.1.1-0.14"

["0.0.5-0.4"]
Juno = "0.2.4-0.3"

["0.1-0.2"]
DiffEqBase = "0.4-0.14"

["0.2.1-0.4"]
DiffEqPDEBase = "0.0-0.3"

["0.3-0.4"]
DiffEqBase = "0.15-1.23"
