["0.0"]
julia = "0.4-0.6"

["0.0.3-0.3"]
Combinatorics = "0.0-0.4"

["0.1-0.2"]
julia = "0.5-0.6"

["0.3"]
julia = "0.6"
SpecialFunctions = "0.0-0.3"

["0.3.1-0.3.7"]
Parameters = "0.0-0.7"

["0.3.4-0.3.7"]
RecipesBase = "0.0-0.2"
