["0.0-0.1"]
DataTables = "0.0.3"
IterableTables = "0.2-0.4"

["0.0-0.3"]
julia = "0.6"
DataValues = "0.1-0.2"
FileIO = "0.4-0.5"
TextParse = "0.1.6-0.1.9"

["0.2"]
IterableTables = "0.4"

["0.2-0.3"]
HTTP = "0.4.2-0.4.3"

["0.3"]
TableTraits = "0.0"
TableTraitsUtils = "0.0-0.1"

["0.3.1"]
IterableTables = "0.5"
