["0.0"]
AxisArrays = "0.0-0.2"
Bio = "0.1-0.4"
DataFrames = "0.1-0.10"
IntervalTrees = "0.0-0.3"
RLEVectors = "0.0-0.3"

["0.0-0.1"]
julia = "0.5-0.6"

["0.1"]
AxisArrays = "0.1.3-0.2"
Compat = "0.17-0.33"
DataTables = "0.0.3"
GenomicFeatures = "0.2"
RLEVectors = "0.3.2"
