["0.1"]
julia = "0.4-0.6"

["0.1.0-0.1.1"]
Nemo = "0.4"

["0.1.2"]
Nemo = "0.4.1"

["0.1.3"]
Nemo = "0.4.1-0.5"

["0.1.4"]
Nemo = "0.5"

["0.1.5"]
Nemo = "0.5.1"

["0.2"]
julia = "0.5-0.6"

["0.2.0"]
Nemo = "0.6.0-0.6.1"

["0.2.1"]
Nemo = "0.6.2"
