["0.1"]
julia = "0.3-0.6"
Compat = "0.0-0.31"

["0.1-0.2"]
Hiccup = "0.0-0.1"
HttpCommon = "0.0-0.3"
HttpServer = "0.0-0.2"
Lazy = "0.1-0.11"
URIParser = "0.0-0.2"
WebSockets = "0.0-0.2"

["0.2"]
julia = "0.4-0.6"

["0.2.3"]
Compat = "0.7.9-0.31"
