["0.0"]
julia = "0.3-0.6"
JavaCall = "0.3.1-0.5"

["0.0-0.1"]
Compat = "0.0-0.31"

["0.0-0.2"]
Requires = "0.1-0.4"

["0.1"]
julia = "0.4-0.6"
JavaCall = "0.4.1-0.5"

["0.1-0.2"]
DBAPI = "0.0-0.1"

["0.2"]
julia = "0.5-0.6"
Compat = "0.17-0.31"
JavaCall = "0.5"
