["0.1-0.2"]
julia = "0.6"
CUDAdrv = "0.5"

["0.1.0"]
CUBLAS = "0.0-0.2"
CUDAnative = "0.4-0.5"

["0.1.1"]
CUBLAS = "0.2.2"

["0.1.1-0.2"]
CUDAnative = "0.5"
NNlib = "0.1"

["0.1.1-0.2.0"]
CUDNN = "0.4"

["0.2"]
CUDAapi = "0.1"
