["0.0-0.2"]
Homebrew = "0.0-0.6"

["0.0.1-0.0.3"]
BinDeps = "0.0-0.8"
Images = "0.2-0.5"

["0.0.1-0.0.14"]
julia = "0.3-0.7"

["0.0.3-0.0.16"]
ZipFile = "0.1-0.5"

["0.0.4"]
ImageView = "0.1.3-0.6"

["0.0.4-0.1"]
Images = "0.4.4-0.5"

["0.0.4-0.2"]
BinDeps = "0.3.4-0.8"
Glob = "1.0-1.1"

["0.0.5-0.1"]
ImageView = "0.1.4-0.6"

["0.0.14-0.0.16"]
Compat = "0.0-0.52"

["0.0.15"]
julia = "0.4-0.7"

["0.0.16"]
julia = "0.3-0.7"

["0.1"]
julia = "0.4-0.7"
Compat = "0.8.7-0.52"

["0.2"]
julia = "0.5-0.7"
ColorTypes = "0.0-0.6"
Compat = "0.18-0.52"
FileIO = "0.0-0.6"
FixedPointNumbers = "0.3-0.4"
ImageCore = "0.0-0.5"
ImageView = "0.3-0.6"
