["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.44"

["0.0.1-0.0.3"]
JSON = "0.1-0.5"

["0.0.4-0.2"]
JSON = "0.1-0.16"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8-0.44"

["0.2"]
julia = "0.5-0.6"

["0.2-0.3"]
GeoInterface = "0.2-0.3"

["0.3"]
julia = "0.6"
JSON = "0.9-0.16"
