["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.31"

["0.0.1-0.0.3"]
JSON = "0.1-0.5"

["0.0.4-0.2"]
JSON = "0.1-0.13"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8-0.31"

["0.2"]
julia = "0.5-0.6"
GeoInterface = "0.2"
