["0.0"]
julia = "0.3-0.6"
Docile = "0.0-0.5"

["0.0-0.2"]
Compat = "0.0-0.31"

["0.1-0.2"]
julia = "0.4-0.6"

["0.3"]
julia = "0.5-0.6"
Compat = "0.18-0.31"

["0.3-0.4"]
LinearMaps = "0.0-1.0"
RecipesBase = "0.0-0.2"
SugarBLAS = "0.0"
UnicodePlots = "0.0-0.2"

["0.4"]
julia = "0.6"
