["1.0"]
Cairo = "0.0-0.3"
Lexicon = "0.0-0.1"

["1.0-1.1"]
StatsBase = "0.1-0.19"

["1.0.0"]
julia = "0.1-0.6"
Docile = "0.0-0.5"

["1.0.1"]
julia = "0.3-0.6"
Logging = "0.0-0.3"

["1.1"]
julia = "0.6"
Combinatorics = "0.0-0.4"
Plots = "0.0-0.13"
RecipesBase = "0.0-0.2"
