["0.0"]
julia = "0.4-0.6"

["0.0.1-0.0.3"]
JuMP = "0.1-0.18"
PATHSolver = "0.0-0.2"

["0.0.4-0.0.5"]
JuMP = "0.13-0.18"
PATHSolver = "0.0.3-0.2"

["0.0.5-0.2"]
NLsolve = "0.7-0.13"

["0.0.9"]
PATHSolver = "0.0.6-0.2"

["0.0.9-0.2"]
JuMP = "0.14-0.18"

["0.1"]
PATHSolver = "0.1-0.2"

["0.1-0.2"]
julia = "0.5-0.6"

["0.2"]
PATHSolver = "0.2"
