["0.0-0.1"]
DiffEqBase = "0.6-0.13"
RecipesBase = "0.1-0.2"

["0.0-0.6"]
julia = "0.5-0.6"

["0.2"]
DiffEqBase = "0.14-0.15"

["0.3"]
DiffEqBase = "1.0-1.5"

["0.4"]
DiffEqBase = "1.3-1.5"

["0.4-0.9"]
RecursiveArrayTools = "0.6-0.12"

["0.5"]
DiffEqBase = "1.6"

["0.6"]
DiffEqBase = "1.7-1.17"

["0.7-0.8"]
DiffEqBase = "1.12-1.17"

["0.7-0.9"]
julia = "0.6"

["0.8-0.9"]
DistributedArrays = "0.1-0.4"

["0.9"]
DiffEqBase = "1.18-1.22"
