["0.0-0.1"]
julia = "0.5-0.7"

["0.0-0.1.2"]
Iterators = "0.1-0.3"

["0.0-0.1.3"]
IntervalSets = "0.0-0.1"

["0.0-0.2"]
RangeArrays = "0.1-0.2"

["0.0.4-0.1"]
Compat = "0.19-0.53"

["0.1.4-0.2"]
IntervalSets = "0.1"

["0.2"]
julia = "0.6-0.7"
IterTools = "0.1-0.2"

["0.2.1"]
Compat = "0.33-0.53"
