["0.0"]
StackTraces = "0.1"

["0.0-0.3"]
julia = "0.5-0.6"
JSON = "0.8-0.16"
Mocking = "0.3-0.4"

["0.2-0.3"]
Compat = "0.17-0.44"

["0.4-0.5"]
julia = "0.6"
Compat = "0.37-0.44"
JSON = "0.16.1-0.16.3"
Syslogs = "0.0"
