["0.0-0.1"]
ArrayViews = "0.1-0.6"
DataFrames = "0.1-0.10"
Optim = "0.1-0.4"

["0.0-0.1.1"]
julia = "0.3-0.6"

["0.0.2-0.1"]
Compat = "0.0-0.37"

["0.1"]
NMF = "0.0-0.3"
StatsBase = "0.1-0.19"

["0.1.1-0.1.2"]
Roots = "0.1-0.4"

["0.1.2"]
julia = "0.4-0.6"

["0.2"]
julia = "0.5-0.6"
ArrayViews = "0.6"
Compat = "0.9-0.37"
DataFrames = "0.8-0.10"
NMF = "0.2.5-0.3"
Optim = "0.6-0.10"
Roots = "0.2-0.4"
ScikitLearnBase = "0.0.4-0.3"
StatsBase = "0.10-0.19"
