["0.1.0-0.1.1"]
julia = "0.1-0.6"

["0.1.2-0.1.7"]
julia = "0.2-0.6"
HTTPClient = "0.1-0.2"
LibExpat = "0.0-0.3"

["0.1.2-0.1.8"]
Codecs = "0.1-0.4"

["0.1.2-0.1.9"]
Calendar = "0.1-0.4"

["0.1.8"]
julia = "0.3-0.6"
HTTPClient = "0.1.4"
LibExpat = "0.0.8"

["0.1.9-0.1.13"]
HTTPClient = "0.1-0.2"
LibExpat = "0.0-0.3"

["0.1.9-0.2"]
julia = "0.4-0.6"

["0.1.12-0.3"]
JSON = "0.1-0.15"

["0.1.13-0.3.0"]
BinDeps = "0.0-0.6"
WinRPM = "0.1-0.2"

["0.2-0.3"]
LightXML = "0.1-0.5"
Requests = "0.0-0.5"
URIParser = "0.0-0.2"

["0.3"]
julia = "0.5-0.6"

["0.3.1"]
Compat = "0.17-0.33"
MbedTLS = "0.1-0.5"
