["0.0"]
julia = "0.1-0.7"

["0.1-0.3.5"]
julia = "0.2-0.7"

["0.3.6-0.7.0"]
julia = "0.3-0.7"

["0.7.1-0.7.2"]
julia = "0.4-0.7"

["0.7.3-0.7.4"]
julia = "0.3-0.7"

["0.7.5"]
julia = "0.4-0.7"

["0.7.6-0.7.14"]
julia = "0.3-0.7"

["0.7.15"]
julia = "0.5-0.7"

["0.7.16-0.8"]
julia = "0.3-0.7"

["0.9-0.26"]
julia = "0.4-0.7"

["0.27-0.43"]
julia = "0.5-0.7"

["0.33-0.53"]
DelimitedFiles = "0.7"
Mmap = "0.7"
SharedArrays = "0.7"
Test = "0.7"

["0.37-0.53"]
Dates = "0.7"

["0.38-0.53"]
Base64 = "0.7"

["0.41-0.53"]
IterativeEigensolvers = "0.7"
Printf = "0.7"
SuiteSparse = "0.7"
Unicode = "0.7"

["0.44-0.53"]
julia = "0.6-0.7"

["0.47-0.53"]
Random = "0.7"
SparseArrays = "0.7"

["0.48-0.53"]
Libdl = "0.7"
LinearAlgebra = "0.7"

["0.50-0.53"]
Distributed = "0.7"
REPL = "0.7"
Serialization = "0.7"

["0.52-0.53"]
InteractiveUtils = "0.7"
Pkg = "0.7"

["0.53"]
LibGit2 = "0.7"
