["0.0"]
julia = "0.4-0.6"
ArrayViews = "0.6.4"

["0.0.4"]
IntervalWavelets = "0.0"
NFFT = "0.1.1"
VoronoiCells = "0.1.1-0.1.4"
Wavelets = "0.4.1-0.6"

["0.0.5-0.0.6"]
Compat = "0.8.4-0.33"
IntervalWavelets = "0.0.4"
NFFT = "0.1.4-0.2"
VoronoiCells = "0.1.3-0.1.4"
Wavelets = "0.5.1-0.6"
