["0.0-0.3"]
julia = "0.4-0.6"

["0.0.1"]
Images = "0.3.3-0.5"

["0.0.2"]
Images = "0.4.4-0.5"

["0.0.3-0.0.4"]
Images = "0.4.20-0.5"

["0.1"]
Images = "0.4.30-0.5"

["0.2.0-0.2.4"]
Images = "0.4.40-0.5"

["0.2.4-0.5"]
Combinatorics = "0.0-0.4"

["0.2.5-0.4.3"]
Images = "0.2-0.5"

["0.2.6-0.5"]
StatsBase = "0.1-0.19"

["0.2.7-0.3.1"]
LightGraphs = "0.5.2-0.11"

["0.3.2-0.5"]
LightGraphs = "0.6.1-0.11"

["0.4"]
julia = "0.5-0.6"

["0.4-0.5"]
Primes = "0.1-0.2"
ProgressMeter = "0.0-0.5"

["0.4.1-0.5"]
Hwloc = "0.1-0.6"

["0.4.4-0.5"]
RecipesBase = "0.0-0.2"

["0.4.4-0.5.2"]
Images = "0.7-0.11"

["0.5"]
julia = "0.6"

["0.5.3-0.5.4"]
ImageFiltering = "0.0-0.2"
ImageMorphology = "0.0"

["0.5.4"]
GeoStatsBase = "0.0"
GeoStatsDevTools = "0.0"
