["0.0"]
julia = "0.4-0.6"

["0.0-0.2"]
Colors = "0.4-0.8"
Gtk = "0.1-0.13"

["0.0.2-0.2"]
Cairo = "0.0-0.3"
Graphics = "0.1-0.2"

["0.0.6-0.2"]
NumericIO = "0.0-0.2"

["0.1"]
julia = "0.5-0.6"

["0.2"]
julia = "0.6"
