["0.1"]
TranscodingStreams = "0.1-0.4"

["0.1-0.4"]
julia = "0.6"

["0.2"]
TranscodingStreams = "0.2-0.4"

["0.2.1-0.4"]
BinDeps = "0.0-0.6"
WinRPM = "0.1-0.3"

["0.3-0.4"]
TranscodingStreams = "0.3-0.4"
