["0.4-0.5"]
Conda = "0.1-0.7"

["0.4-0.6"]
julia = "0.4-0.6"
BinDeps = "0.0-0.6"
Compat = "0.0-0.37"
WinRPM = "0.1-0.3"

["0.6"]
Conda = "0.2-0.7"

["0.7"]
julia = "0.5-0.6"
BinDeps = "0.3.19-0.6"
Conda = "0.5-0.7"
