["0.0.1-0.0.2"]
Polynomial = "0.1"

["0.0.1-0.0.3"]
julia = "0.1-0.6"

["0.0.2-0.3"]
Reexport = "0.0-0.1"

["0.0.3-0.1"]
Polynomials = "0.0-0.2"

["0.0.4-0.0.11"]
julia = "0.3-0.6"

["0.0.7-0.0.11"]
Compat = "0.0-0.44"

["0.1"]
julia = "0.4-0.6"

["0.1.0"]
Compat = "0.7.15-0.44"

["0.1.1"]
Compat = "0.8.4-0.44"

["0.2"]
julia = "0.5-0.6"
Compat = "0.18-0.44"

["0.2-0.3"]
Polynomials = "0.1-0.2"
SpecialFunctions = "0.0-0.3"

["0.3"]
julia = "0.6"
AbstractFFTs = "0.0-0.2"
FFTW = "0.0"

["0.3.4"]
Compat = "0.32-0.44"
