["0.0"]
julia = "0.4-0.6"

["0.0-0.1"]
Nettle = "0.1-0.3"

["0.0-0.1.4"]
SymDict = "0.0-0.1"

["0.0-0.2"]
Requests = "0.0-0.5"
URIParser = "0.1.2-0.3"

["0.0-0.3"]
IniFile = "0.2-0.3"
JSON = "0.1-0.16"
Retry = "0.0-0.1"
XMLDict = "0.0-0.1"

["0.0.17"]
Compat = "0.0-0.44"

["0.1-0.2"]
julia = "0.5-0.6"
HttpCommon = "0.0-0.3"

["0.1.5-0.3"]
SymDict = "0.1.2-0.1.3"

["0.2-0.3"]
DataStructures = "0.2-0.7"
MbedTLS = "0.1-0.5"

["0.3"]
julia = "0.6"
HTTP = "0.5.4-0.5.7"
