["0.0"]
julia = "0.4-0.7"
AWSCore = "0.0-0.3"

["0.0-0.2"]
AWSSQS = "0.0-0.3"

["0.0.1"]
ZipFile = "0.1-0.5"

["0.0.2-0.2"]
DataStructures = "0.2-0.7"
InfoZIP = "0.0-0.1"

["0.0.14-0.1"]
Nettle = "0.1-0.3"

["0.0.14-0.1.2"]
SymDict = "0.0-0.1"

["0.0.14-0.2"]
AWSEC2 = "0.0-0.3"
AWSIAM = "0.0-0.3"
AWSS3 = "0.0-0.3"
Glob = "1.0-1.1"
JSON = "0.1-0.16"

["0.0.17"]
Compat = "0.0-0.53"

["0.1"]
AWSCore = "0.1-0.3"

["0.1-0.2"]
julia = "0.5-0.7"
AWSSNS = "0.0-0.3"
FNVHash = "0.0-0.1"
Primes = "0.1-0.2"
Retry = "0.0-0.2"

["0.1.3-0.2"]
SymDict = "0.1.2-0.1.3"

["0.2"]
AWSCore = "0.2-0.3"
