["0.1-0.2"]
julia = "0.3-0.6"
MAT = "0.1-0.4"
NumericExtensions = "0.2-0.6"

["0.3-0.4"]
MAT = "0.2.9-0.4"

["0.3.0-0.3.3"]
julia = "0.3.6-0.6"
NumericExtensions = "0.6.2"

["0.3.4-0.4"]
julia = "0.4-0.6"
Coverage = "0.0-0.4"
FactCheck = "0.2.8-0.4"
