["0.0-0.1"]
julia = "0.4-0.7"
Graphs = "0.2-0.9"

["0.0-0.2"]
Colors = "0.4-0.8"
Gadfly = "0.1-0.6"
GraphViz = "0.0-0.1"

["0.0-0.2.2"]
KernelDensityEstimate = "0.0-0.3"

["0.0-0.3"]
Distributions = "0.1-0.15"
NLsolve = "0.1-0.13"

["0.0.2-0.2.2"]
TransformUtils = "0.0-0.1"

["0.2"]
julia = "0.5-0.7"

["0.2.0-0.2.9"]
Graphs = "0.7.1-0.9"

["0.2.3-0.2.6"]
KernelDensityEstimate = "0.2.1-0.3"

["0.2.4-0.3"]
Optim = "0.1-0.13"

["0.2.6-0.2.9"]
HDF5 = "0.1-0.8"

["0.2.6-0.3"]
JLD = "0.5-0.8"
ProgressMeter = "0.0-0.5"

["0.2.7-0.2.9"]
KernelDensityEstimate = "0.2.3-0.3"

["0.2.10-0.2.11"]
Graphs = "0.8-0.9"
KernelDensityEstimate = "0.2.6-0.3"

["0.2.10-0.3"]
Compat = "0.18-0.53"
HDF5 = "0.8.5-0.8.8"

["0.3"]
julia = "0.6-0.7"
Graphs = "0.9"
KernelDensityEstimate = "0.3"
