["0.0-0.1"]
julia = "0.4-0.6"
Graphs = "0.2-0.8"

["0.0-0.2"]
Colors = "0.4-0.8"
Distributions = "0.1-0.15"
Gadfly = "0.1-0.6"
GraphViz = "0.0-0.1"
NLsolve = "0.1-0.13"

["0.0-0.2.2"]
KernelDensityEstimate = "0.0-0.2"

["0.0.2-0.2.2"]
TransformUtils = "0.0"

["0.2"]
julia = "0.5-0.6"

["0.2.0-0.2.9"]
Graphs = "0.7.1-0.8"

["0.2.3-0.2.6"]
KernelDensityEstimate = "0.2.1-0.2.6"

["0.2.4-0.2.11"]
Optim = "0.1-0.11"

["0.2.6-0.2.9"]
HDF5 = "0.1-0.8"

["0.2.6-0.2.11"]
JLD = "0.5-0.8"
ProgressMeter = "0.0-0.5"

["0.2.7-0.2.9"]
KernelDensityEstimate = "0.2.3-0.2.6"

["0.2.10-0.2.11"]
Compat = "0.18-0.39"
Graphs = "0.8"
HDF5 = "0.8.5-0.8.8"
KernelDensityEstimate = "0.2.6"
