["0.1"]
julia = "0.4-0.7"
DataFrames = "0.1-0.10"

["0.1-0.2"]
JSON = "0.1-0.16"
Requests = "0.0-0.5"

["0.1.3-0.2"]
Compat = "0.7.9-0.52"

["0.2"]
julia = "0.5-0.7"
DataFrames = "0.1-0.11"
Lazy = "0.1-0.12"
