["0.9"]
julia = "0.6"
ArgParse = "0.2-0.5"
BioSequences = "0.5-0.8"
BioSymbols = "1.0-1.2"
BufferedStreams = "0.0-0.3"
DataStructures = "0.2-0.7"
Distributions = "0.1-0.15"
FMIndexes = "0.0-0.1"
Glob = "1.0-1.1"
IntArrays = "0.0-0.1"
IntervalTrees = "0.0-0.4"
Libz = "0.0-0.2"
StatsBase = "0.1-0.19"
SuffixArrays = "0.0-0.1"
