["0.0-0.3"]
Documenter = "0.3-0.12"
FunctionWrappers = "0.0-0.1"
NamedTuples = "1.0"
NullableArrays = "0.0.7-0.1"

["0.0-0.4"]
julia = "0.5-0.6"
Requires = "0.3-0.4"

["0.0-0.7"]
DataStructures = "0.4.5-0.7"

["0.4"]
NamedTuples = "2.0-2.1"

["0.4-0.7"]
Documenter = "0.9-0.12"

["0.4.0"]
IterableTables = "0.0"

["0.4.1"]
IterableTables = "0.0-0.4"

["0.5-0.6"]
IterableTables = "0.1-0.4"

["0.5-0.7"]
julia = "0.6"
DataValues = "0.0.2-0.3"
NamedTuples = "3.0.2-4.0"
Requires = "0.4.3"

["0.7"]
IterableTables = "0.5"
MacroTools = "0.3.7"
TableTraits = "0.0"
