["0.0"]
julia = "0.1-0.7"

["0.0-0.2"]
BioSeq = "0.1-0.4"
FastaIO = "0.1-0.3"
Formatting = "0.1-0.3"
LightXML = "0.1-0.5"
PyCall = "0.0-1.15"
PyPlot = "1.0-2.3"
Requests = "0.0-0.5"

["0.1-0.2"]
julia = "0.4.2-0.7"

["0.2"]
BaseTestDeprecated = "0.1"
