["0.0.1-0.0.4"]
julia = "0.2-0.4"

["0.0.2"]
HttpCommon = "0.0-0.3"
HttpServer = "0.0-0.2"
Meddle = "0.0"

["0.0.3-0.0.4"]
HttpCommon = "0.0.3-0.3"
HttpServer = "0.0.4-0.2"
Meddle = "0.0.3-0.0.6"

["0.0.5-0.0.6"]
julia = "0.3-0.4"
HttpCommon = "0.0-0.3"
HttpServer = "0.0-0.2"
Meddle = "0.0"

["0.0.6"]
Compat = "0.0-0.31"
