["0.0"]
MathProgBase = "0.5"

["0.0-0.2"]
julia = "0.4-0.6"

["0.0.2-0.2"]
Compat = "0.8.6-0.44"

["0.1-0.4"]
MathProgBase = "0.5-0.6"

["0.3-0.4"]
Compat = "0.18-0.44"

["0.3-0.5"]
julia = "0.5-0.6"

["0.5"]
MathProgBase = "0.6-0.7"
