["0.0"]
julia = "0.3-0.6"
Compat = "0.0-0.39"
Zlib = "0.1"

["0.0-0.1"]
FixedPointNumbers = "0.0-0.2"
Images = "0.2-0.5"
SIUnits = "0.0-0.1"

["0.0.2-0.3"]
FileIO = "0.0-0.6"

["0.1"]
julia = "0.4-0.6"
Compat = "0.8.7-0.39"

["0.1-0.3"]
Libz = "0.0-0.2"

["0.2-0.3"]
julia = "0.5-0.6"
AxisArrays = "0.0-0.2"
Colors = "0.4-0.8"
ColorVectorSpace = "0.0-0.5"
FixedPointNumbers = "0.3-0.4"
ImageAxes = "0.0-0.4"
ImageCore = "0.0-0.5"
MappedArrays = "0.0"
Quaternions = "0.0-0.3"
Ranges = "0.0"
StaticArrays = "0.0-0.6"
Unitful = "0.0-0.5"

["0.3.2"]
Compat = "0.18-0.39"
