["1.0-1.1"]
julia = "0.3-0.6"
Color = "0.2.10-0.4"

["1.0-1.2"]
Cairo = "0.0-0.3"
DataFrames = "0.1-0.10"

["1.1"]
Lexicon = "0.0-0.1"
Logging = "0.0-0.3"

["1.1-1.2"]
StatsBase = "0.1-0.18"

["1.2"]
julia = "0.4-0.6"
Colors = "0.4-0.8"
