["0.1-0.2"]
julia = "0.2-0.7"

["0.1-0.3"]
PyCall = "0.0-1.15"
PyPlot = "1.0-2.3"

["0.3-0.4"]
julia = "0.4-0.7"

["0.4"]
Compat = "0.10-0.54"

["0.4-0.6"]
Lazy = "0.11.4-0.12"
PyCall = "1.7.2-1.15"
PyPlot = "2.2.4-2.3"

["0.5"]
julia = "0.5-0.7"

["0.5-0.6"]
Compat = "0.17-0.54"

["0.6"]
julia = "0.6-0.7"
TableTraits = "0.0-0.1"
TableTraitsUtils = "0.0-0.1"

["0.6.1-0.6.3"]
DataValues = "0.0-0.3"
