["0.1-0.2"]
Compat = "0.0-0.31"
FactCheck = "0.0-0.4"

["0.1-0.4"]
FunctionalCollections = "0.1-0.3"
JSON = "0.1-0.13"

["0.1.0-0.1.5"]
julia = "0.1-0.6"

["0.1.6-0.2"]
julia = "0.3-0.6"

["0.3"]
julia = "0.4-0.6"
Compat = "0.9-0.31"

["0.4"]
julia = "0.5-0.6"
Compat = "0.17-0.31"
