["0.1-0.2"]
DeferredFutures = "0.3-0.5"
Iterators = "0.2-0.3"

["0.1-0.3"]
julia = "0.5-0.6"
AutoHashEquals = "0.0.10-0.1"
DataStructures = "0.5-0.7"
LightGraphs = "0.7-0.10"
Memento = "0.1-0.2"
ResultTypes = "0.1-1.0"

["0.3"]
Compat = "0.18-0.31"
DeferredFutures = "0.5"
IterTools = "0.1"
