["0.0"]
julia = "0.4-0.7"

["0.0-0.3"]
BinDeps = "0.0-0.8"

["0.0.1-0.0.5"]
ForwardDiff = "0.0-0.1"

["0.0.6-0.3"]
ForwardDiff = "0.2-0.7"

["0.1-0.3"]
julia = "0.5-0.7"

["0.3"]
FunctionWrappers = "0.1"
