["0.0.1"]
julia = "0.2-0.6"

["0.0.2-0.1"]
julia = "0.4-0.6"

["0.0.6"]
Compat = "0.0-0.39"

["0.1"]
Compat = "0.8-0.39"

["0.1-0.2"]
BinDeps = "0.0-0.8"
Homebrew = "0.0-0.6"

["0.2"]
julia = "0.5-0.6"
Compat = "0.17-0.39"
