["0.0-0.1"]
julia = "0.5-0.7"
DiffEqBase = "1.0.2-2.10"
NLsolve = "0.1-0.13"

["0.1-0.2"]
Compat = "0.17-0.53"

["0.2"]
julia = "0.6-0.7"
DiffEqBase = "3.0-3.4"
NLsolve = "0.14-1.0"
Reexport = "0.0-0.1"
