["0.0"]
julia = "0.4-0.6"
ConjugatePriors = "0.1-0.2"
Distributions = "0.1-0.14"

["0.1-0.2"]
PDMats = "0.5.1-0.7"

["0.1-0.3"]
julia = "0.5-0.6"
Distributions = "0.11-0.14"
ForwardDiff = "0.0-0.5"

["0.2"]
Stats = "0.0-0.1"

["0.2-0.3"]
Mamba = "0.3-0.11"
ProgressMeter = "0.0-0.4"
