["0.0-0.2"]
Iterators = "0.1-0.3"
RecursiveArrayTools = "0.0.2-0.14"

["0.0-0.3"]
julia = "0.5-0.6"

["0.1-0.5"]
DiffEqBase = "0.11-2.10"

["0.2-0.3"]
Compat = "0.19-0.44"

["0.3-0.5"]
RecursiveArrayTools = "0.8-0.14"

["0.4-0.5"]
julia = "0.6"
