["0.0-0.2"]
Iterators = "0.1-0.3"
RecursiveArrayTools = "0.0.2-0.12"

["0.0-0.3"]
julia = "0.5-0.6"

["0.1-0.4"]
DiffEqBase = "0.11-1.22"

["0.2-0.3"]
Compat = "0.19-0.31"

["0.3-0.4"]
RecursiveArrayTools = "0.8-0.12"

["0.4"]
julia = "0.6"
