["0.0"]
ImmutableArrays = "0.0"

["0.0.1-0.0.2"]
julia = "0.2-0.6"

["0.0.3"]
julia = "0.2"

["0.0.4-0.0.8"]
julia = "0.3-0.6"

["0.0.7-0.1.0"]
Compat = "0.0-0.31"

["0.1-0.2"]
julia = "0.4-0.6"
FixedSizeArrays = "0.0-0.2"

["0.1.1-0.2"]
Compat = "0.8-0.31"

["0.3"]
julia = "0.5-0.6"

["0.3-0.4"]
Compat = "0.9.4-0.31"
StaticArrays = "0.0-0.6"

["0.4"]
julia = "0.6"
