["0.0-0.2"]
julia = "0.5-0.7"

["0.0-0.5"]
DiffEqDiffTools = "0.0-0.2"

["0.0.1"]
DiffEqBase = "0.0-0.14"

["0.0.2"]
DiffEqBase = "0.1.2-0.14"

["0.0.3-0.0.4"]
DiffEqBase = "0.2-0.14"

["0.1"]
DiffEqBase = "0.15"

["0.2-0.5"]
DiffEqBase = "0.15-2.10"

["0.2.2-0.5"]
Compat = "0.17-0.49"

["0.3-0.5"]
julia = "0.6-0.7"

["0.4-0.5"]
ForwardDiff = "0.0-0.7"

["0.5"]
DiffEqCallbacks = "0.0-0.8"
QuadGK = "0.1-0.2"
