["0.0-0.2"]
julia = "0.5-0.6"

["0.0.1"]
DiffEqBase = "0.0-0.14"

["0.0.2"]
DiffEqBase = "0.1.2-0.14"

["0.0.3-0.0.4"]
DiffEqBase = "0.2-0.14"

["0.1"]
DiffEqBase = "0.15"

["0.2-0.3"]
DiffEqBase = "0.15-2.6"

["0.2.2-0.3"]
Compat = "0.17-0.37"

["0.3"]
julia = "0.6"
