["0.0"]
julia = "0.4-0.6"

["0.0-0.2"]
DataArrays = "0.0-0.6"
DataFrames = "0.1-0.10"
MAT = "0.1-0.3"
Quaternions = "0.0-0.3"
StatsBase = "0.1-0.18"

["0.0-0.2.1"]
Plots = "0.0-0.12"

["0.0.1"]
PyPlot = "1.0-2.3"

["0.1"]
julia = "0.5-0.6"
FixedSizeArrays = "0.0-0.2"

["0.1-0.2"]
RecipesBase = "0.0-0.2"

["0.2"]
julia = "0.6"
StaticArrays = "0.0-0.6"
