["0.1"]
julia = "0.4-0.6"
BinDeps = "0.0-0.6"

["0.1.1-0.1.2"]
Compat = "0.8.4-0.33"

["0.1.3-0.2"]
Compat = "0.9.1-0.33"

["0.2"]
julia = "0.5-0.6"

["0.2-0.3"]
BinDeps = "0.6"

["0.3"]
julia = "0.6"
