["0.0"]
julia = "0.1-0.6"
FixedSizeArrays = "0.0-0.2"

["0.0-0.1"]
FixedPointNumbers = "0.0-0.2"

["0.1"]
julia = "0.3-0.6"
Compat = "0.0-0.37"
Docile = "0.0-0.5"

["0.2"]
julia = "0.4-0.6"
FixedPointNumbers = "0.1-0.2"

["0.3-0.5"]
julia = "0.5-0.6"

["0.3-0.6"]
FixedPointNumbers = "0.3-0.4"

["0.3.1-0.3.2"]
Compat = "0.16-0.37"

["0.3.3"]
Compat = "0.17-0.37"

["0.3.4-0.5.1"]
Compat = "0.18-0.37"

["0.5.2-0.6.2"]
Compat = "0.26-0.37"

["0.6"]
julia = "0.6"

["0.6.3-0.6.6"]
Compat = "0.32-0.37"
