["0.1-0.3"]
julia = "0.6"
ForwardDiff = "0.5-0.7"
IterTools = "0.1-0.2"
LsqFit = "0.0-0.3"
NearestNeighbors = "0.0-0.3"
OrdinaryDiffEq = "2.17-2.35"
Requires = "0.4.3"
StaticArrays = "0.5-0.6"
StatsBase = "0.8.2-0.19"
