["0.1-0.2"]
julia = "0.5-0.6"
NullableArrays = "0.0-0.1"

["0.1-0.3"]
Compat = "0.17-0.44"
PooledArrays = "0.0.2-0.1"

["0.1.0-0.1.8"]
WeakRefStrings = "0.1-0.2"

["0.1.9-0.3.1"]
WeakRefStrings = "0.1-0.4"

["0.2-0.3"]
DataStructures = "0.2-0.7"

["0.3"]
julia = "0.6"
DataValues = "0.0-0.3"
